var n = 0;
var otazky = new Array();
var spatneOtazky = new Array();
var odpovezene = new Array();

var spravne = 0;
var spatne = 0;

var otazka;

var x = 0;

function start() {
	zalozOtazky();
	document.getElementById('start').remove();

	document.getElementById('otazka').style.visibility = 'visible';
	//document.getElementById('odpoved').style.visibility = 'visible';
	document.getElementById('check').style.visibility = 'visible';
	document.getElementById('otazkaCislo').style.visibility = 'visible';

	nactiOtazku();
}

function nactiOtazku() {
	if (otazky.length <= n) {
		document.getElementById("form").style.visibility = 'hidden';
		document.getElementById("otazkaCislo").style.visibility = 'hidden';
		document.getElementById("dalsi").style.visibility = 'hidden';

		document.getElementById("check").innerHTML = '<p>Správných odpovědí: ' + spravne + '</p>' +
			'<p>Špatných odpovědí: ' + spatne + '</p>' +
			'<button id="spatneOtazky" type="button" onclick=nactiSpatne()>Znovu špatné otázky</button>';
		return;
	}

	while (true) {
		x = Math.floor((Math.random() * otazky.length));
		if (odpovezene.indexOf(x) >= 0)
			;
		else
			break;
	}

	document.getElementById('otazkaCislo').innerHTML = "Otázka " + (n + 1) + " z " + (otazky.length);
	document.getElementById("check").style.visibility = 'hidden';
	document.getElementById("dalsi").style.visibility = 'hidden';
	otazka = otazky[x];
	document.getElementById('otazka').innerHTML = '<div id="form">' +
		otazka.otazka + ': <br><input id="id1" type="text" name="question" onkeypress="isEnter()">' +
		'<input id="end" type="button" value="Odpovědět" onclick=check()>' +
		'</div>';

	document.getElementById("id1").focus();
}

function nactiSpatne() {
	document.getElementById("form").style.visibility = 'visible';
	document.getElementById("otazkaCislo").style.visibility = 'visible';
	document.getElementById("dalsi").style.visibility = 'visible';
	document.getElementById('otazka').style.visibility = 'visible';
	document.getElementById('check').style.visibility = 'visible';

	otazky = [];
	otazky = spatneOtazky;
	spatneOtazky = [];
	n = 0;
	x = 0;
	spravne = 0;
	spatne = 0;
	odpovezene = [];
	nactiOtazku();
}

function isEnter(e) {
	if ((event.which == 13 || event.keyCode == 13)) {
		if (document.getElementById("dalsi").style.visibility == 'visible') {
			nactiOtazku();
		} else {
			check();
		}
	}
}

function check() {
	//document.getElementById("check").innerHTML = document.getElementById("id1").value;
	document.getElementById("check").style.visibility = 'visible';
	if (document.getElementById("id1").value == otazka.odpoved) {
		document.getElementById("check").innerHTML = '<p style="color:green">Správná odpověď</p>';
		spravne++;
	} else {
		document.getElementById("check").innerHTML = '<p style="color:red">Špatně!</p>' +
			'Správná odpověď je: ' + otazka.odpoved;
		spatne++;
		spatneOtazky.push(otazka)
	}

	if (otazky.length > n) {
		odpovezene.push(x);
		n++;

		document.getElementById("end").style.visibility = 'hidden';
		document.getElementById("dalsi").style.visibility = 'visible';
	}
	/*else{
	 document.getElementById("form").remove();
	 document.getElementById("otazkaCislo").remove();;
	 document.getElementById("check").innerHTML = '<p>Správných odpovědí: ' + spravne + '</p>' + 
	 '<p>Špatných odpovědí: ' + spatne + '</p>'
	 }*/
}

function zalozOtazky() {
	pridejOtazku("abduct", "unést");
	pridejOtazku("abduction", "únos např. dítěte");
	pridejOtazku("abductor", "únosce");
	pridejOtazku("abolish", "zrušit");
	pridejOtazku("abolishment", "zrušení");
	pridejOtazku("abolitionist", "země, které zrušily trest smrti");
	pridejOtazku("abuse", "zneužívat, týrat, zneužívání, týrání");
	pridejOtazku("abuse", "zneužití");
	pridejOtazku("abuse", "zneužití, zneužívat");
	pridejOtazku("abuse", "urážka, nadávka");
	pridejOtazku("abuse of public official powers", "zneužití pravomoci veřejného činitele");
	pridejOtazku("abuse physically", "dopouštět se fyzického násilí");
	pridejOtazku("access", "přístup");
	pridejOtazku("accessible", "dostupný");
	pridejOtazku("accession", "vstup");
	pridejOtazku("accidental", "náhodný");
	pridejOtazku("accident victim", "oběť nehody");
	pridejOtazku("account", "bankovní účet");
	pridejOtazku("account", "účet");
	pridejOtazku("acquit", "zprostit viny");
	pridejOtazku("Act", "zákon");
	pridejOtazku("act", "čin, jednání, zákon");
	pridejOtazku("actual bodily harm", "lehké ublížení na zdraví");
	pridejOtazku("addiction", "návyk, sklon, závislost");
	pridejOtazku("additional", "doplňkový");
	pridejOtazku("add up", "dávat jako součet, znamenat");
	pridejOtazku("adjust", "nastavit, přizpůsobit");
	pridejOtazku("adopt", "přijmout");
	pridejOtazku("advance", "pokrok");
	pridejOtazku("adviser", "poradce");
	pridejOtazku("affair", "otázka, záležitost, věc");
	pridejOtazku("aggravating circumstance", "přitěžující okolnost");
	pridejOtazku("aim at", "zaměřit se na");
	pridejOtazku("aim to", "usilovat o co");
	pridejOtazku("Air Rescue Service", "letecká záchranná služba");
	pridejOtazku("alarm", "poplašné zařízení");
	pridejOtazku("alert", "ostražitý, ve střehu, ve stavu pohotovosti");
	pridejOtazku("alias", "falešné jméno, přezdívka");
	pridejOtazku("alien", "cizinec");
	pridejOtazku("Alien Police", "služba pohraniční a cizinecké policie");
	pridejOtazku("allegation", "obvinění z údajného trestného činu");
	pridejOtazku("alleged", "údajný");
	pridejOtazku("alleged", "údajný, domnělý");
	pridejOtazku("allow or dismiss the appeal", "přijmout nebo zamítnout odvolání");
	pridejOtazku("amendment", "dodatek");
	pridejOtazku("annually", "ročně, každoročně");
	pridejOtazku("anonymously", "anonymně");
	pridejOtazku("answerable", "odpovědný");
	pridejOtazku("anti-spyware software", "program pro zabezpečení PC proti proniknutí");
	pridejOtazku("applications for", "žádost o");
	pridejOtazku("appoint", "jmenovat");
	pridejOtazku("appointment", "jmenování (do funkce, hodnosti)");
	pridejOtazku("apprehend", "zadržet");
	pridejOtazku("apprehend", "zatknout");
	pridejOtazku("apprehension", "zadržení");
	pridejOtazku("apprehension of", "vzetí do vazby");
	pridejOtazku("appropriate", "přivlastnit si");
	pridejOtazku("appropriately", "náležitě");
	pridejOtazku("approve", "schválit");
	pridejOtazku("approve of", "považovat za správné");
	pridejOtazku("arest warrant", "příkaz k zatčení, zatykač");
	pridejOtazku("armed", "ozbrojený");
	pridejOtazku("Armenians", "Arméni");
	pridejOtazku("around the clock", "24 hodin denně");
	pridejOtazku("arrest", "zatčení, zajištění, zadržení");
	pridejOtazku("arson", "žhářství");
	pridejOtazku("artificially inflate the price", "uměle vyhnat cenu nahoru");
	pridejOtazku("ascertain", "zjistit");
	pridejOtazku("assailant", "útočník, násilník");
	pridejOtazku("assault", "napadení, přepadení, útok");
	pridejOtazku("assault", "útok, napadení");
	pridejOtazku("assaulting a public official", "napadení veřejného činitele");
	pridejOtazku("assault on", "napadení koho, útok na");
	pridejOtazku("assign to", "přidělit k");
	pridejOtazku("Assistant Inspector of Constabulary", "zástupce ředitele ředitelství policie");
	pridejOtazku("assume", "přijmout, vzít na sebe");
	pridejOtazku("assumption", "předpoklad");
	pridejOtazku("at large", "na svobodě");
	pridejOtazku("attempt", "pokusit se, pokus");
	pridejOtazku("attempted offence", "pokus trestného činu");
	pridejOtazku("attempted rape", "pokus o znásilnění");
	pridejOtazku("attempt to escape", "pokus o útěk");
	pridejOtazku("at the very fabric of free society", "v samé podstatě svobodné společnosti");
	pridejOtazku("authorities", "úřady");
	pridejOtazku("available", "k dispozici");
	pridejOtazku("avoid", "vyhnout se, vyvarovat se");
	pridejOtazku("Bachelor Degree", "bakalářský stupeň studia");
	pridejOtazku("badge", "odznak");
	pridejOtazku("bail", "kauce");
	pridejOtazku("bailiff", "soudní zřízenec");
	pridejOtazku("bank robbery", "bankovní loupež");
	pridejOtazku("bankruptcy fraudpodvody", "spojené s vyhlašováním konkurzu");
	pridejOtazku("bank statement", "výpis z účtu");
	pridejOtazku("batterer", "násilník");
	pridejOtazku("battery", "ublížení na zdraví, fyzické napadení, použití násilí proti osobě");
	pridejOtazku("battery", "ublížení na zdraví");
	pridejOtazku("be addressed through", "být řešen čím");
	pridejOtazku("be alerted to", "být varován, být upozorněn na");
	pridejOtazku("bear the name", "opatřit značkou, logem");
	pridejOtazku("be at large", "být na svobodě");
	pridejOtazku("be aware of something", "být si vědom čeho");
	pridejOtazku("because of", "kvůli, z důvodu, vzhledem k");
	pridejOtazku("be entrusted with power", "smít svěřeny pravomoci");
	pridejOtazku("be involved in", "být zapojen do, angažovaný v, zúčastněný v");
	pridejOtazku("belief", "víra, přesvědčení");
	pridejOtazku("be on probation", " být v podmínce, na svobodě při podmíněném prominutí trestu");
	pridejOtazku("be staffed by", " být personálně obsazen");
	pridejOtazku("be subject to", "podléhat čemu");
	pridejOtazku("beyond any reasonable doubt", "nad vší pochybnost");
	pridejOtazku("bias related crime", "trestná činnost související s předsudky, předpojatostí");
	pridejOtazku("bilateral agreement", "bilaterální, dvoustranná dohoda");
	pridejOtazku("billion", "miliarda");
	pridejOtazku("biological", "material takingodběr biologického materiálu");
	pridejOtazku("blackmail", "vydírání, vyděračství");
	pridejOtazku("blade", "čepel");
	pridejOtazku("blatant, obvious", "očividný, výrazný, zřejmý, jednoznačný");
	pridejOtazku("blood test", "krevní zkouška");
	pridejOtazku("board", "rada, výbor");
	pridejOtazku("bodies", "orgány");
	pridejOtazku("bogus", "padělaný, nepravý, falešný");
	pridejOtazku("bolt", "západka, zástrčka");
	pridejOtazku("bomb", "disposal zneškodňování výbušnin");
	pridejOtazku("border", "hranice");
	pridejOtazku("border checks", "hraniční kontroly");
	pridejOtazku("border control", "pohraniční kontrola");
	pridejOtazku("border security", "bezpečnostna hranicích");
	pridejOtazku("botched investigationnedbale", "provedené vyšetřování");
	pridejOtazku("break", "porouchat se");
	pridejOtazku("break in", "vloupání");
	pridejOtazku("break the law", "porušit zákon");
	pridejOtazku("bribery", "uplácení");
	pridejOtazku("bring", "předvést");
	pridejOtazku("bullying", "šikanování");
	pridejOtazku("burglary", "vloupání");
	pridejOtazku("call for", "vyzvat, žádat");
	pridejOtazku("canine corps", "psovodi");
	pridejOtazku("capital crimes", "trestné činy, za něž je možné uložit trest smrti");
	pridejOtazku("capital punishment", "trest smrti");
	pridejOtazku("capital punishment, death penalty, death sentence", "trest smrti");
	pridejOtazku("capitol parlament", "sídlo vlády");
	pridejOtazku("capitol police", "ochranná služba");
	pridejOtazku("captivity", "zbavení osobní svobody, omezování os svobody");
	pridejOtazku("car boot", "zavazadlový prostor vozidla");
	pridejOtazku("car boot sale", "prodej z kufru auta");
	pridejOtazku("carjacking", "únos (auta)");
	pridejOtazku("carry due identification", "být řádně označen");
	pridejOtazku("carry out expertise", "provádět expertízu, vypracovat odborné posudky");
	pridejOtazku("cash", "hotovost");
	pridejOtazku("catch out", "přistihnout");
	pridejOtazku("cause", "zapřičinit, způsobit");
	pridejOtazku("cause", "příčina");
	pridejOtazku("causeway", "silnice vedená po hrázi");
	pridejOtazku("caution", "obezřetnost, opatrnost");
	pridejOtazku("cease", "zastavit");
	pridejOtazku("central government", "centrální vláda");
	pridejOtazku("challenging", "náročný, podnětný, představující výzvu");
	pridejOtazku("charge", "obvinění, obžaloba");
	pridejOtazku("charge somebody with", "obvinit něhoho z");
	pridejOtazku("charge with", "obvinit z");
	pridejOtazku("charting", "obsahující, popisující");
	pridejOtazku("check", "kontrolovat, zkontrolovat");
	pridejOtazku("chemist's", "britská lékárna");
	pridejOtazku("child abuse", "zneužívání dítěte");
	pridejOtazku("child neglect", "zanedbání povinné výživy, výchovy");
	pridejOtazku("child pornography", "dětská pornografie");
	pridejOtazku("Christians", "křesťané");
	pridejOtazku("circumstance", "okolnost");
	pridejOtazku("citation", "předvolání, obsílka");
	pridejOtazku("Civil Division", "občansko právní kolegium");
	pridejOtazku("civil proceedings", "občansko právní řízení");
	pridejOtazku("civil support staff", "občanští, civilní zaměstnanci");
	pridejOtazku("claim", "tvrzení");
	pridejOtazku("claim", "žádost, požadavek");
	pridejOtazku("clarification", "objasnění");
	pridejOtazku("collect additional informations", "hromažďovat doplňující informace");
	pridejOtazku("collect", "evidence získávat, shromažďovat důkazy");
	pridejOtazku("collection", "vyšetřování");
	pridejOtazku("combat", "boj, potírání");
	pridejOtazku("combat", "bojovat");
	pridejOtazku("combat crime", "bojovat s trestnou činností");
	pridejOtazku("command", "velení");
	pridejOtazku("commencing the act", "zahájení trestního stíhání");
	pridejOtazku("commit", "spáchat");
	pridejOtazku("commit a crime", "spáchat trestný čin");
	pridejOtazku("commit crime", "páchat trestnou činnost");
	pridejOtazku("commit criminal acts", "páchat, dopustit se trestných činů");
	pridejOtazku("commit somebody to the court", "předat soudu");
	pridejOtazku("commit suicide", "spáchat sebevraždu");
	pridejOtazku("committal proceeding", "řízení ve věci");
	pridejOtazku("committee", "výbor, komise");
	pridejOtazku("commodities fraud", "podvody s komoditami");
	pridejOtazku("common", "obvyklý, běžný, společný");
	pridejOtazku("common assault", "fyzické napadení");
	pridejOtazku("communication skills", "komunikativní dovednosti");
	pridejOtazku("community body", "orgán společenství");
	pridejOtazku("community policing", "policej. činnost ve spolupráci s míst. obyvatelstvem (jako kdysi četnictvo)");
	pridejOtazku("community service", "veřejně prospěšné práce");
	pridejOtazku("complaint", "stížnost");
	pridejOtazku("complaint for breaching the law", "stížnost pro porušení zákona");
	pridejOtazku("computer crime", "počítačová kriminalita");
	pridejOtazku("con artist", "notorický podvodník");
	pridejOtazku("concealment", "utajování");
	pridejOtazku("concept", "pojem");
	pridejOtazku("concern", "znepokojení");
	pridejOtazku("concern", "zajímat se");
	pridejOtazku("conclusions", "závěry");
	pridejOtazku("conditional cessation of prosecution", "podmíněné zastavení trestního stíhání");
	pridejOtazku("conditional discharge", "podmíněné propuštění");
	pridejOtazku("conditionally", "podmíněně");
	pridejOtazku("conduct", "provádět, vést, řídit");
	pridejOtazku("confidence", "důvěra");
	pridejOtazku("confiscate", "zabavit");
	pridejOtazku("conform to", "odpovídat čemu");
	pridejOtazku("consecutive", "nepřetržitý, po sobě jdoucí");
	pridejOtazku("consequence", "následek");
	pridejOtazku("consider", "považovat");
	pridejOtazku("constable", "strážník, policista");
	pridejOtazku("constabulary", "ředitelství policie");
	pridejOtazku("constantly alert", "neustále ve stavu pohotovosti, ve střehu");
	pridejOtazku("constitute a criminal offence", "zakládat trestný čin");
	pridejOtazku("constitute a reason", "zakládat důvod");
	pridejOtazku("constitutional official", "ústavní činitel");
	pridejOtazku("consumer fraud", "poškozování spotřebitele");
	pridejOtazku("contempt of court", "pohrdání soudem");
	pridejOtazku("continuous self education", "kontinuální vzdělávání, soustavné sebevzdělávání");
	pridejOtazku("contour", "linie, obrys, tvar");
	pridejOtazku("convict", "odsoudit, usvědčit, uznat/shledat vinným");
	pridejOtazku("convict, convicted", "odsoudit, odsouzený");
	pridejOtazku("convicted", "odsouzený");
	pridejOtazku("conviction", "usvědčení, rozsudek");
	pridejOtazku("conviction", "výrok o vině");
	pridejOtazku("conviction", "odsouzení");
	pridejOtazku("convict of", "konstatovat vinu");
	pridejOtazku("convict of a crime", "odsoudit za trestný čin");
	pridejOtazku("cooperate", "spolupracovat");
	pridejOtazku("copyright theft", "porušování autorského práva");
	pridejOtazku("corner", "ovládnout");
	pridejOtazku("coroner", "úřední ohledavač mrtvol");
	pridejOtazku("corporate dishonesty", "firemní nepoctivost");
	pridejOtazku("corporate fraud", "firemní podvody");
	pridejOtazku("corruption", "korupce");
	pridejOtazku("cost", "náklady, cena");
	pridejOtazku("cough", "syrup sirup proti kašli");
	pridejOtazku("counsel", "obhájce");
	pridejOtazku("counterfeit", "padělaný");
	pridejOtazku("counterfeit", "padělat");
	pridejOtazku("counterfeiting", "padělání");
	pridejOtazku("county", "správní oblast, okres v rámci jednotlivých států USA");
	pridejOtazku("court", "soud");
	pridejOtazku("court of appeal", "odvolací soud");
	pridejOtazku("court of trial", "soud");
	pridejOtazku("crackdown", "policejní zásah, zákrok");
	pridejOtazku("crackdown", "zásah, zákrok");
	pridejOtazku("crash", "rozbít, havarovat");
	pridejOtazku("create", "vytvářet");
	pridejOtazku("credibility", "důvěryhodnost");
	pridejOtazku("credible", "důvěryhodný, věrohodný, spolehlivý");
	pridejOtazku("credit card", "úvěrová karta");
	pridejOtazku("credit card frauds", "podvody s kreditními kartami");
	pridejOtazku("creed", "přesvědčení, vyznání");
	pridejOtazku("crime", "trestný čin, zločin");
	pridejOtazku("crime prevention", "prevence kriminality");
	pridejOtazku("crime rate", "míra kriminality, nápad trestné činnosti");
	pridejOtazku("crime registry", "registr trestné činnosti");
	pridejOtazku("crime-related information", "informace, týkající se trestné činnosti");
	pridejOtazku("crimes against humanity", "zločiny proti lidskosti");
	pridejOtazku("crimes against property", "trestné činy proti majetku");
	pridejOtazku("crime scene", "místo činu");
	pridejOtazku("crime scene", "místo trestného činu");
	pridejOtazku("crime spree", "série trestných činů");
	pridejOtazku("crime", "kriminalita, trestná činnost");
	pridejOtazku("criminal", "pachatel trestného činu");
	pridejOtazku("Criminal and Investigation Police", "služba kriminální policie a vyšetřování");
	pridejOtazku("criminal cases", "trestní případy");
	pridejOtazku("Criminal Code", "trestní zákon");
	pridejOtazku("criminal conspiracy", "zločinné spiknutí");
	pridejOtazku("criminal court order", "trestní příkaz");
	pridejOtazku("Criminal Division", "trestní kolegium");
	pridejOtazku("criminal intelligence", "informace, týkající se trestné činnosti");
	pridejOtazku("criminalistics laboratory", "kriminalistická laboratoř");
	pridejOtazku("criminal offence", "trestný čin");
	pridejOtazku("criminal offences", "trestné činy");
	pridejOtazku("Criminal Police and Investigation Department", "služba kriminální policie a vyšetřování");
	pridejOtazku("Criminal Procedure Code", "trestní řád");
	pridejOtazku("criminal proceedings", "trestní řízení/stíhání");
	pridejOtazku("cross-border", "přeshraniční");
	pridejOtazku("cross burnings", "pálení křížů");
	pridejOtazku("Crown Court", "královský soud");
	pridejOtazku("crucial", "rozhodující, klíčový");
	pridejOtazku("cruel", "zvláště trýznivý");
	pridejOtazku("cruelly", "zvláště trýznivým způsobem");
	pridejOtazku("cruelty", "mučivé útrapy");
	pridejOtazku("curb", "omezit");
	pridejOtazku("custody", "vazba");
	pridejOtazku("custody petition", "návrh na uvalení vazby");
	pridejOtazku("customs", "celní správa");
	pridejOtazku("customs control", "celní kontrola");
	pridejOtazku("dactyloscopic print", "daktyloskopická stopa");
	pridejOtazku("damage", "ztráta");
	pridejOtazku("damage", "škoda, újma, poškození");
	pridejOtazku("date rape", "znásilnění mezi partnery ne v manželském svazku");
	pridejOtazku("deadbolt", "bezpečnostní zámek");
	pridejOtazku("dealing", "prodej");
	pridejOtazku("deal with", "zabývat se, jednat");
	pridejOtazku("deal with", "zabývat se něčím, projednávat co");
	pridejOtazku("deal with", "zvládnout, vypořádat se");
	pridejOtazku("deal with", "řešit, zabývat se");
	pridejOtazku("death", "úmrtí");
	pridejOtazku("death penalty", "trest smrti");
	pridejOtazku("death sentence", "trest smrti");
	pridejOtazku("deceit", "podvod, klam");
	pridejOtazku("deception", "podvod, klam, trik, podvod s totožností");
	pridejOtazku("defendant", "obžalovaný");
	pridejOtazku("defendant", "obviněný, obžalovaný");
	pridejOtazku("deference", "úcta, ohled");
	pridejOtazku("define", "definovat, psát");
	pridejOtazku("defraud", "oklamat, ošidit");
	pridejOtazku("degree", "stupeň");
	pridejOtazku("deliberate", "úmyslný");
	pridejOtazku("delinquency", "delikvence, kriminalita, zločinnost");
	pridejOtazku("demand", "požadovat");
	pridejOtazku("demand a testimony", "požadovat vysvětlení");
	pridejOtazku("demand personal identification", "požadovat prokázání totožnosti");
	pridejOtazku("department", "oddělení");
	pridejOtazku("dependency", "závislost");
	pridejOtazku("deposit", "uložit, vklad");
	pridejOtazku("deputy", "zástupce");
	pridejOtazku("deputy", "náměstek, zástupce");
	pridejOtazku("deputy sheriff", "zástupce šerifa");
	pridejOtazku("designated contact point", "určené kontaktní místo");
	pridejOtazku("detachment", "odloučené pracoviště");
	pridejOtazku("detain", "zajistit");
	pridejOtazku("detect", "dopadnout, vypátrat");
	pridejOtazku("detect", "objevit, zjistit");
	pridejOtazku("detect", "zjišťovat, odhalovat");
	pridejOtazku("detection of offenders", "vypátrání pachatelů");
	pridejOtazku("deter", "zabránit");
	pridejOtazku("deter", "odstrašit, odradit");
	pridejOtazku("determine", "určit, stanovit, rozhodnout");
	pridejOtazku("determine", "určit");
	pridejOtazku("determine", "určit, stanovit");
	pridejOtazku("determine", "stanovit, určit");
	pridejOtazku("deterrent", "odrazující");
	pridejOtazku("deterrent", "odstrašující prostředek");
	pridejOtazku("device", "zařízení, přístroj");
	pridejOtazku("devolve", "postoupit");
	pridejOtazku("different level", "odlišná úroveň");
	pridejOtazku("direct danger of severe injury or death", "bezprostřední nebezpečí závažného zranění nebo smrti");
	pridejOtazku("disaster scene", "místo neštěstí, katastrofy");
	pridejOtazku("discontinue", "přerušit");
	pridejOtazku("disguised weapons", "skryté zbraně");
	pridejOtazku("dismiss", "zamítnout");
	pridejOtazku("dispute", "spor, hádka");
	pridejOtazku("distinguish", "rozlišit, rozeznávat");
	pridejOtazku("distract", "rozptýlit, vyrušit, obrátit pozornost");
	pridejOtazku("district", "správní oblast, obvod, okres");
	pridejOtazku("disturb", "porušit");
	pridejOtazku("disturbing the peace", "narušování veřejného pořádku");
	pridejOtazku("diverse", "různý, rozličný");
	pridejOtazku("Doctor Degree", "doktorský stupeň studia");
	pridejOtazku("documentation gathering", "shromažďování dokumentace");
	pridejOtazku("domestic abuse", "týrání svěřené osoby");
	pridejOtazku("domestic violence", "domácí násilí");
	pridejOtazku("dose", "dávka");
	pridejOtazku("doubt", "pochybovat");
	pridejOtazku("draft", "návrh");
	pridejOtazku("drive from", "odvést z, vyvést z");
	pridejOtazku("driving offence", "porušení pravidel silničního provozu");
	pridejOtazku("drug store", "americká lékárna");
	pridejOtazku("drug trafficking", "nekalé obchodování s drogami");
	pridejOtazku("drunk and disorderly", "opilost a výtržnictví");
	pridejOtazku("dumping of rubbish", "vysypávání odpadků");
	pridejOtazku("dumpster diving", "probírání se odpadky (v průmyslové špionáži)");
	pridejOtazku("dupe", "napálit, podvést, oklamat");
	pridejOtazku("duties", "povinnosti, úkoly");
	pridejOtazku("duty", "povinnosti, úkoly");
	pridejOtazku("economic crime", "hospodářská trestná činnost, hospodářská kriminalita");
	pridejOtazku("e-dealer", "prodejce na internetu");
	pridejOtazku("education and training", "vzdělávání a výcvik");
	pridejOtazku("efficiency and effectiveness", "efektivita a účinnost");
	pridejOtazku("elect", "volit");
	pridejOtazku("electrical equipment", "elektronika");
	pridejOtazku("elude", "vyhnout se (obratně)");
	pridejOtazku("eluding technique", "technika, s jejíž pomocí se pachatel vyhne prozrazení");
	pridejOtazku("embed", "pevně zasadit, zapustit");
	pridejOtazku("embezzlement", "zpronevěra, defraudace");
	pridejOtazku("embrace", "zahrnovat");
	pridejOtazku("emerge", "objevit se");
	pridejOtazku("emergency assistance", "pomoc v naléhavých případech");
	pridejOtazku("emergency equipment", "vybavení pro případ nouze, záchranné zařízení");
	pridejOtazku("emergency event", "mimořádná událost, stav nouze");
	pridejOtazku("emergency response team", "zásahová jednotka");
	pridejOtazku("employee of the state", "státní zaměstnanec");
	pridejOtazku("encourage new recruit", "spodporovat, stimulovat nové uchazeče");
	pridejOtazku("enforce", "vynutit si, prosadit");
	pridejOtazku("enforce law", "prosazovat právo");
	pridejOtazku("enforce the law", "prosazovat zákon");
	pridejOtazku("engage in", "zabývat se, praktikovat");
	pridejOtazku("engine", "motor");
	pridejOtazku("enhance", "posilovat");
	pridejOtazku("enhancing", "posílení");
	pridejOtazku("entail", "znamenat");
	pridejOtazku("enter", "vstoupit, vstup");
	pridejOtazku("entrust", "svěřit");
	pridejOtazku("entry", "vstup");
	pridejOtazku("environmental crime", "trestné činy proti životnímu prostředí");
	pridejOtazku("epaulette", "nárameník");
	pridejOtazku("EPG, enhanced protection glazing", "bezpečnostní autosklo");
	pridejOtazku("equipment", "vybavení");
	pridejOtazku("escape", "útěk, utéct, uprchnout");
	pridejOtazku("espionage", "špionáž, vyzvědačství");
	pridejOtazku("essencial", "zásadní");
	pridejOtazku("establish", "ustanovit, zřídit");
	pridejOtazku("establishment", "stálý stav");
	pridejOtazku("establish the budget", "připravit rozpočet");
	pridejOtazku("ethnic cleansing", "etnické čistky");
	pridejOtazku("European Court of Human Rights", "Evropský soud pro lidská práva");
	pridejOtazku("European Court of Justice", "Evropský soudní dvůr");
	pridejOtazku("eventually overturned", "nakonec změněný");
	pridejOtazku("evidence", "důkaz, důkazy");
	pridejOtazku("examination", "prověřování");
	pridejOtazku("examine", "zkoumat, přezkoumat, přešetřit");
	pridejOtazku("exceed", "překročit, přesáhnout");
	pridejOtazku("excise duty", "nepřímá, spotřební daň");
	pridejOtazku("exclusively", "výhradně");
	pridejOtazku("execute", "popravit");
	pridejOtazku("execution", "poprava");
	pridejOtazku("Executive committee", "Výkonný výbor");
	pridejOtazku("exemplify", "ilustrovat, doložit příkladem");
	pridejOtazku("exercise", "uplatňovat, vykonávat");
	pridejOtazku("exercise authority", "uplatňovat pravomoc");
	pridejOtazku("exercise one's duties", "vykonávat, plnit své povinnosti, vykonávat službu");
	pridejOtazku("expect", "očekávat");
	pridejOtazku("expert evidence", "důkaz prokázaný soudním znalcem");
	pridejOtazku("expertise statement", "znalecký posudek");
	pridejOtazku("expose", "vystavit, odhalit");
	pridejOtazku("external border", "vnější hranice");
	pridejOtazku("extortion", "vydírání, vymáhání, vynucování");
	pridejOtazku("extreme fenomenon", "extrémní jev");
	pridejOtazku("acilitate", "ulehčit, pomoci");
	pridejOtazku("acilitate", "usnadnit, zjednodušit");
	pridejOtazku("acilitating", "usnadňující");
	pridejOtazku("ail", "selhat, neuspět");
	pridejOtazku("ail", "zkrachovat");
	pridejOtazku("airness", "spravedlnost, čestnost, slušnost");
	pridejOtazku("ake", "goods padělané zboží");
	pridejOtazku("atal", "smrtelný");
	pridejOtazku("elon", "těžký zločinec");
	pridejOtazku("elony", "závažný trestný čin");
	pridejOtazku("elony", "těžký zločin");
	pridejOtazku("ictional", "smyšlený, románový");
	pridejOtazku("ile", "spis");
	pridejOtazku("ile report", "vyplňovat hlášení");
	pridejOtazku("inal solution", "konečné řešení (Židovské otázky)");
	pridejOtazku("inancial fraud", "finanční podvody");
	pridejOtazku("inancial gain", "finanční zisk");
	pridejOtazku("inding", "zjištění");
	pridejOtazku("inding", "poznatek");
	pridejOtazku("ine", "pokuta, pokutovat");
	pridejOtazku("ingerprint", "otisk prstu");
	pridejOtazku("ingerprint", "identificationdaktyloskopie");
	pridejOtazku("ingertip", "špička prstu");
	pridejOtazku("firearms", "střelné zbraně");
	pridejOtazku("first aid", "první pomoc");
	pridejOtazku("fitting", "instalování, instalace");
	pridejOtazku("flee", "uprchnout, utéci");
	pridejOtazku("floods", "záplavy povodně");
	pridejOtazku("fool around with", "pohrávat si s");
	pridejOtazku("footage", "video/foto záznam, dokumentace");
	pridejOtazku("forbid", "zakazovat");
	pridejOtazku("force", "násilí, síla");
	pridejOtazku("force", "násilím něčeho dosáhnout, vynutit si vstup, vypáčit, vyrazit");
	pridejOtazku("forced entry", "násilný vstup do objektu, budovy, bytu");
	pridejOtazku("forensic", "soudní, forenzní");
	pridejOtazku("forensic laboratory", "kriminalistická laboratoř");
	pridejOtazku("forensic science", "forenzní věda");
	pridejOtazku("forge", "padělat");
	pridejOtazku("forgery", "padělání");
	pridejOtazku("fowl", "drůbež");
	pridejOtazku("fragment", "úlomek, střep");
	pridejOtazku("fragmentation", "roztříštění");
	pridejOtazku("fragmented", "roztříštěný");
	pridejOtazku("fraud", "podvod");
	pridejOtazku("fraudster", "podvodník");
	pridejOtazku("fraudulent emails", "podvodné e-maily");
	pridejOtazku("fraud within corporations", "podvody pracovníků uvnitř firmy");
	pridejOtazku("free movement of people", "volný pohyb osob");
	pridejOtazku("friction", "tření");
	pridejOtazku("fugitive", "osoba na útěku, uprchlík");
	pridejOtazku("fugitives", "uprchlíci");
	pridejOtazku("fulfil", "plnit");
	pridejOtazku("full time study", "denní studium");
	pridejOtazku("further vocational training", "další odborné/profesní vzdělávání/výcvik");
	pridejOtazku("gain", "zisk");
	pridejOtazku("gain", "získat");
	pridejOtazku("garment", "kus oděvu, nebo prádla");
	pridejOtazku("garments", "oděvy");
	pridejOtazku("gather facts", "shromažďovat fakta");
	pridejOtazku("gather facts", "zjišťovat skutečnosti/fakta");
	pridejOtazku("General Assembly", "Valné shromáždění");
	pridejOtazku("General Secretariat", "Generální sekretariát");
	pridejOtazku("genetics", "genetika");
	pridejOtazku("genocide", "genocida, masakr, vyhlazení");
	pridejOtazku("get in touch", "vejít v kontakt");
	pridejOtazku("get involved", "účastnit se");
	pridejOtazku("give rise", "vyvolat");
	pridejOtazku("glazing", "zasklení");
	pridejOtazku("go beyond", "přesahovat rámec");
	pridejOtazku("goods", "zboží");
	pridejOtazku("grab", "propadnout, neprávem si přivlastnit");
	pridejOtazku("graffiti", "grafitti, nápisy na zdech a veřejně přístupných místech");
	pridejOtazku("grievous bodily harm", "těžké ublížení na zdraví");
	pridejOtazku("growing", "pěstování");
	pridejOtazku("guest", "host");
	pridejOtazku("guideline", "pravidlo, pokyn");
	pridejOtazku("guilty", "vinen");
	pridejOtazku("hack another computer", "proniknout do jiného počítače");
	pridejOtazku("hamper", "bránit, překážet");
	pridejOtazku("handle", "manipulovat, zacházet s něčím");
	pridejOtazku("handling stolen goods", "překupnictví kradeného zboží");
	pridejOtazku("handwriting", "rukopis");
	pridejOtazku("handwriting identification", "písmoznalectví");
	pridejOtazku("hang around, hang round", "nečinně postávat, potloukat se kolem");
	pridejOtazku("harbor patrol", "přístavní hlídka");
	pridejOtazku("harm", "újma, ublížení, zranění");
	pridejOtazku("hate crimes", "trestné činy rasově motivované a proti lidskosti");
	pridejOtazku("hate groups", "extremisté, skupiny");
	pridejOtazku("hatred toward particular groups", "nenávist, zášť vůči konkrétním skupinám");
	pridejOtazku("have legal personality", "mít právní subjektivitu");
	pridejOtazku("headquarters", "ústředí, centrála, ředitelství");
	pridejOtazku("health care fraud", "podvody v poskytování zdravotní péče");
	pridejOtazku("hear a case", "projednat");
	pridejOtazku("hear a person", "vyslechnout");
	pridejOtazku("hearing", "projednávání, slyšení");
	pridejOtazku("hearing", "výslech");
	pridejOtazku("High Court", "nejvyšší soud");
	pridejOtazku("high-impact economic crime", "závažná hiospodářská trestná činnost");
	pridejOtazku("High Public Prosecutornej", "vyšší státní zástupce");
	pridejOtazku("highway patrol", "dálniční policie");
	pridejOtazku("hijacking", "únos (letadla)");
	pridejOtazku("hit-and-run", "ujetí z místa nehody");
	pridejOtazku("home confinement", "domácí vězení");
	pridejOtazku("Home Secretary", "ministr vnitra");
	pridejOtazku("homicide", "vražda, zabití");
	pridejOtazku("homophobic", "homofobní, nemající rád homosexuály");
	pridejOtazku("horseback unit", "jednotka jízdní policie");
	pridejOtazku("hostility", "nepřátelství, zášť, odpor");
	pridejOtazku("House of Lords", "Sněmovna lordů");
	pridejOtazku("huge", "obrovský, ohromný");
	pridejOtazku("hugely", "obrovsky");
	pridejOtazku("human trafficking", "obchodování s lidmi");
	pridejOtazku("humiliate", "utiskovat, utlačovat, ponižovat");
	pridejOtazku("humiliation", "útisk, útlak");
	pridejOtazku("dentity date", "identifikační údaje");
	pridejOtazku("dentity fraud", "nemajetkový podvod");
	pridejOtazku("dentity theft", "krádež identity");
	pridejOtazku("dentity theft", "zneužití, krádež identity, poškozování cizích práv");
	pridejOtazku("ignition", "zapalování");
	pridejOtazku("ignition key", "klíč k zapalování");
	pridejOtazku("illegal downloading", "nelegální stahování");
	pridejOtazku("illegal drug trade", "nelegální obchod s drogami");
	pridejOtazku("illicid drug production", "nezákonná výroba drog");
	pridejOtazku("immigration", "přistěhovalectví, imigrace");
	pridejOtazku("immobiliser", "zařízení, zabraňující v odjezdu s vozidlem");
	pridejOtazku("impact", "dopad, účinek");
	pridejOtazku("impact-resistant", "odolný vůči nárazu");
	pridejOtazku("impairment", "poškození");
	pridejOtazku("implement", "provádět, uskutečňovat");
	pridejOtazku("imply", "předpokládat, obsahovat");
	pridejOtazku("impose", "uložit, uvalit");
	pridejOtazku("imprisonment", "trest odnětí svobody");
	pridejOtazku("incalculable", "nevyčíslitelný, nezměrný");
	pridejOtazku("incapacitation", "zbavení způsobilosti k právním úkonům");
	pridejOtazku("incest", "incest, sexuální zneužití mezi příbuznými");
	pridejOtazku("included on the agenda", "zahrnutý do pořadu jednání");
	pridejOtazku("increasing range", "rozšiřující se nabídka, sortiment");
	pridejOtazku("indecency", "obscénnost, nemravnost");
	pridejOtazku("indefinitely", "nekonečně");
	pridejOtazku("independent in operational matters", "samostatný při rozhodování o úkolech a akcích");
	pridejOtazku("independent office holder", "nezávislýúředník");
	pridejOtazku("indictable offence", "žalovatelný trestný čin, čin soudně trestný");
	pridejOtazku("indictment", "obžaloba, obžalovací spis");
	pridejOtazku("industrial espionage", "průmyslová špionáž");
	pridejOtazku("inerview", "výslech");
	pridejOtazku("inflict", "způsobit");
	pridejOtazku("infraction", "porušení, přestoupení, přestupek");
	pridejOtazku("infringe", "porušit právo, zákon");
	pridejOtazku("ingenuity", "vynalézavost, důvtipnost");
	pridejOtazku("inherent part", "neodmyslitelná část");
	pridejOtazku("injury", "zranění");
	pridejOtazku("innocent", "nevinen, nevinný");
	pridejOtazku("inquire", "dokazovat před soudem");
	pridejOtazku("inquiry", "dokazování před soudem, vyšetřování");
	pridejOtazku("insider trading", "zneužívání informací v obchodním styku");
	pridejOtazku("Inspector of Constabulary", "ředitel ředitelství policie");
	pridejOtazku("inspire", "inspirovat, vnuknout nápad");
	pridejOtazku("installing", "instalace");
	pridejOtazku("insult", "urážka");
	pridejOtazku("insurance", "pojištění");
	pridejOtazku("insurance fraud", "pojišťovací podvody");
	pridejOtazku("intellectual property", "duševní vlastnictví");
	pridejOtazku("intellectual property", "crimezcizení duševního vlastnictví");
	pridejOtazku("intelligence agency", "zpravodajská, výzvědná služba");
	pridejOtazku("intent", "úmysl");
	pridejOtazku("International Criminal Court", "Mezinárodní trestní soud");
	pridejOtazku("International Criminal Tribunal", "Mezinárodní trestní tribunál");
	pridejOtazku("international ties", "mezinárodní vazby");
	pridejOtazku("Internet crime", "internetová kriminalita");
	pridejOtazku("intimidate and disrupt entire communities", "činit nátlak a způsobit rozklad celých komunit");
	pridejOtazku("intimidation and violence", "útlak a násilí");
	pridejOtazku("investigate", "vyšetřovat");
	pridejOtazku("investigate a burglary", "vyšetřovat vloupání");
	pridejOtazku("investigation", "vyšetřování");
	pridejOtazku("investigative", "vyšetřovací");
	pridejOtazku("inviolability", "nedotknutelnost");
	pridejOtazku("involuntary manslaughter", "nedbalostní zabití");
	pridejOtazku("involve", "zahrnovat");
	pridejOtazku("involvement", "zapojení se čeho, angažování se v čem");
	pridejOtazku("IPCC", "nezávislá policejní komise pro vyšetřování stížností");
	pridejOtazku("issue", "otázky, problémy");
	pridejOtazku("issue", "položka, část, vydat, vyslat, zveřejnit, vystavit");
	pridejOtazku("issue an appology", "zveřejnit omluvu");
	pridejOtazku("item", "položka, věc");
	pridejOtazku("jail", "věznice, vězení, uvěznit, poslat do vězení");
	pridejOtazku("jaywalking", "bezohledné přecházení ulice");
	pridejOtazku("jersey", "dres");
	pridejOtazku("jewel", "šperk, klenot");
	pridejOtazku("jewellery", "šperky, klenoty");
	pridejOtazku("Jewish", "židovský");
	pridejOtazku("Jews", "Židé");
	pridejOtazku("judge", "soudce");
	pridejOtazku("judiciary", "justice");
	pridejOtazku("junior officers", "služebně mladší policisté");
	pridejOtazku("jurisdiction", "soudní pravomoc, jurisdikce");
	pridejOtazku("jurisdiction", "jurisdikce, soudní pravomoc");
	pridejOtazku("jury", "porota");
	pridejOtazku("jury trial", "soudní řízení za přítomnosti poroty");
	pridejOtazku("Justice Department", "Ministerstvo spravedlnosti");
	pridejOtazku("justified concern", "oprávěná obava");
	pridejOtazku("juvenile", "mladistvý");
	pridejOtazku("juvenile court", "soud pro mladistvé");
	pridejOtazku("juvenile delinquency", "kriminalita mladistvých");
	pridejOtazku("juvenile delinquent", "mladistvý provinilec");
	pridejOtazku("key operational objecti", "vesklíčové operační úkoly");
	pridejOtazku("kick", "kopnout");
	pridejOtazku("kidnapping", "únos osoby");
	pridejOtazku("kidnapping children via chat rooms", "únos dětí prostřednictvím chatů");
	pridejOtazku("killing in self defence", "zabití, usmrcení v sebeobraně");
	pridejOtazku("lapse", "chyba, omyl");
	pridejOtazku("larceny", "odcizení cizího majetku");
	pridejOtazku("larceny", "krádež, rozkrádání");
	pridejOtazku("larceny", "odcizení, krádež");
	pridejOtazku("launch", "zahájit, spustit");
	pridejOtazku("law-breaking", "porušení práva, zákona");
	pridejOtazku("law enforcement", "bezpečnostní složky, prosazování zákona, policie, úřad šerifa");
	pridejOtazku("law enforcement authorities", "orgány činné v trestním řízení");
	pridejOtazku("law enforcement officers", "policisté, příslušníci bezpečnostních složek");
	pridejOtazku("lead", "vést, řídit");
	pridejOtazku("leadership", "schopnost vést, řídit");
	pridejOtazku("leaflets and posters", "letáky a plakáty");
	pridejOtazku("legal consequences", "právní následky");
	pridejOtazku("legal counsel", "právní zastoupení");
	pridejOtazku("legal prescription drugs", "léky na recept");
	pridejOtazku("legislative tool", "legislativní nástroj");
	pridejOtazku("length", "podrobně, do detailu");
	pridejOtazku("liaison office", "styčný úřad");
	pridejOtazku("life imprisonment", "trest odnění svobody na doživotí");
	pridejOtazku("lifelong study", "celoživotní vzdělávání");
	pridejOtazku("limited powers", "omezené pravomoci");
	pridejOtazku("line of duty", "výkon služby");
	pridejOtazku("littering", "odhazování odpadků");
	pridejOtazku("livestock", "hospodářské zvíře");
	pridejOtazku("loaded gun", "nabitá zbraň");
	pridejOtazku("loan", "půjčka");
	pridejOtazku("local authority areas", "místní územní celky");
	pridejOtazku("local council tax", "daně odváděné obecnímu úřadu, který je má ke své dispozici");
	pridejOtazku("local government", "místní samospráva");
	pridejOtazku("local police authority", "místní policejní instituce a její představitelé");
	pridejOtazku("location", "vypátrání, nalezení");
	pridejOtazku("logistics", "logistika");
	pridejOtazku("magistrate", "soudce nižšího soudu");
	pridejOtazku("magistrate", "úředník se soudní pravomocí");
	pridejOtazku("Magistrate court", "městský soud");
	pridejOtazku("Magistrate's Court", "nižší soud s omezenou jurisdikcí, zabývající se méně závažnými trestnými činy");
	pridejOtazku("maintain", "udržovat, vést, provádět, držet, posílit, podpořit");
	pridejOtazku("maintain records", "uchovávat záznamy");
	pridejOtazku("maintenance", "podpora");
	pridejOtazku("make up", "tvořit, skládat se, představovat");
	pridejOtazku("management skills", "manažerské dovednosti");
	pridejOtazku("manslaughter", "zabití člověka v afektu, nebo z nedbalosti, neúmyslné zabití");
	pridejOtazku("manufacture", "výroba");
	pridejOtazku("manufacturing", "výroba");
	pridejOtazku("marital rape", "znásilnění mezi partnery v manželském svazku");
	pridejOtazku("mark", "stopa, skvrna, šlápota");
	pridejOtazku("mass marketing fraud", "spotřebitelské podvody pomocí médií (internet, telemarketing)");
	pridejOtazku("mass murderer", "masový vrah (str. 93)");
	pridejOtazku("Master Degree", "magisterský stupeň studia");
	pridejOtazku("maturity", "zralost, vyspělost");
	pridejOtazku("means of identification", "identifikační označení");
	pridejOtazku("medical and life insurance", "zdravotní a životní pojištění");
	pridejOtazku("medical exam", "lékařská prohlídka");
	pridejOtazku("mention", "zmínit");
	pridejOtazku("merchandise", "zboží");
	pridejOtazku("Metropolitan Police", "Metropolitní policie města Londýna");
	pridejOtazku("Metropolitan Police Rape Unit", "oddělení metropolitní policie pro vyšetřování případů znásilnění");
	pridejOtazku("middle rank", "poddůstojnická hodnost");
	pridejOtazku("Ministry of the Interior, (Affairs)", "Ministerstvo vnitra");
	pridejOtazku("minors", "nezletilé osoby");
	pridejOtazku("misconduct", "neprofesionální řízení, chování");
	pridejOtazku("misdemeanor", "přečin, méně závažný trestný čin");
	pridejOtazku("missing person", "pohřešovaná osoba");
	pridejOtazku("misuse", "zneužití");
	pridejOtazku("model", "vytvořit, modelovat");
	pridejOtazku("molest", "vykonávat sexuální nátlak");
	pridejOtazku("molestation", "sexuální nátlak");
	pridejOtazku("molester", "pachatel sexuálního nátlaku");
	pridejOtazku("money laundering", "praní peněz");
	pridejOtazku("mortgage fraud", "hypotéční podvody");
	pridejOtazku("motor vehicle laws", "pravidla silničního provozu");
	pridejOtazku("motor vehicle theft", "krádež motorového vozidla");
	pridejOtazku("multiple", "mnohonásobný, mnohočetný");
	pridejOtazku("municipal", "městský");
	pridejOtazku("murder", "vražda, zavrařdit, úkladná vražda");
	pridejOtazku("murder weapon", "vražedná zbraň");
	pridejOtazku("mutual aid agreement", "smlouva o vzájemné pomoci");
	pridejOtazku("national", "celostátní, státní příslušník");
	pridejOtazku("National Central Bureau", "Národní ústředna");
	pridejOtazku("national emblem", "státní znak");
	pridejOtazku("nationality", "národnost");
	pridejOtazku("National Security Strategy", "národní bezpečnostní strategie");
	pridejOtazku("Native Americans", "indiáni");
	pridejOtazku("Nazi", "nacista, nacistický");
	pridejOtazku("negligence, carelessness", "nedbalost, nepozornost");
	pridejOtazku("neo-Nazi", "neonacista");
	pridejOtazku("non-recurring act", "neopakovatelný úkon");
	pridejOtazku("notices", "oznámení, výzvy, žádosti, pátrací oběžníky");
	pridejOtazku("objective", "cíl, operační cíl, úkol, plán");
	pridejOtazku("obliged", "povinen");
	pridejOtazku("observance", "dodržování");
	pridejOtazku("observe", "sledovat");
	pridejOtazku("obstruct", "mařit");
	pridejOtazku("obtain", "obdržet");
	pridejOtazku("obtain", "získat");
	pridejOtazku("obtain conviction", "vyslovit odsuzující rozsudek");
	pridejOtazku("obvious", "očividný");
	pridejOtazku("occupational crimetr", "činnost při výkonu povolání");
	pridejOtazku("occupational speciality", "pracovní zařazení");
	pridejOtazku("occur", "přihodit se, stát se");
	pridejOtazku("offence", "kriminální delikt, trestný čin");
	pridejOtazku("offence", "pohoršení, urážka");
	pridejOtazku("offence", "přestupek, přečin, trestný čin, porušení norem trestního a správního práva");
	pridejOtazku("offender", "pachatel, obviněný");
	pridejOtazku("offensive", "urážlivý, útočný");
	pridejOtazku("Office For Foreign Relations and", "Úřad pro zahraniční styky a informace ÚZSIInformation, (OFRI)");
	pridejOtazku("official", "úředník, funkcionář");
	pridejOtazku("official", "report usnesení");
	pridejOtazku("on account of", "s ohledem na, vzhledem k");
	pridejOtazku("on display", "k prohlídce, vystavený");
	pridejOtazku("on duty, off duty", "ve službě, mimo službu");
	pridejOtazku("on file", "v databázi");
	pridejOtazku("on the basis", "na základě");
	pridejOtazku("on the motion", "na návrh");
	pridejOtazku("open attitude", "otevřenost");
	pridejOtazku("operate", "provozovat spravovat");
	pridejOtazku("operational centre", "operační středisko");
	pridejOtazku("operational heads", "vedoucí operační pracovníci");
	pridejOtazku("opportunist", "příležitostný");
	pridejOtazku("opportunist", "prospěchář");
	pridejOtazku("option", "možnost");
	pridejOtazku("ordeal", "utrpení");
	pridejOtazku("organized crime", "organizovaný zločin");
	pridejOtazku("Ottoman", "vládce tureckého impéria");
	pridejOtazku("out of court settlement", "mimosoudní vyrovnání");
	pridejOtazku("overbilling", "fakturování vyšší částky");
	pridejOtazku("over-burdened", "přetížený");
	pridejOtazku("overcrowded", "přeplněnný");
	pridejOtazku("overlap", "překrývat, krýt se s něčím zahrnovat");
	pridejOtazku("overseas", "cizí, zámořský");
	pridejOtazku("overtime", "práce přesčas");
	pridejOtazku("overturn the sentence", "změnit rozsudek");
	pridejOtazku("paperwork", "administrativa");
	pridejOtazku("paragraph", "odstavec");
	pridejOtazku("paramilitaries", "ozbrojenci");
	pridejOtazku("parole", "podmíněné, dočasné propuštění");
	pridejOtazku("particular", "jednotlivý, určitý");
	pridejOtazku("particular field", "specifická oblast");
	pridejOtazku("part time study", "kombinované studium");
	pridejOtazku("pass himself off", "vydávat se za někoho");
	pridejOtazku("password", "heslo");
	pridejOtazku("patrol", "hlídkovat");
	pridejOtazku("patrolling and reconnaisance flights", "hlídkové a průzkumné lety");
	pridejOtazku("pattern", "model, schéma");
	pridejOtazku("pattern", "předloha, původní e mail (jeden z významů)");
	pridejOtazku("pedestrian", "chodec");
	pridejOtazku("penal law", "trestní právo");
	pridejOtazku("penalty", "trest, pokuta");
	pridejOtazku("pension fund crime", "trestná činnost spojená s machinacemi v penzijních fondech");
	pridejOtazku("perceive", "vnímat, chápat");
	pridejOtazku("peremptory act", "neodkladný úkon");
	pridejOtazku("perform", "vykonávat");
	pridejOtazku("performance", "výkon");
	pridejOtazku("perform duties", "vykonávat, plnit své povinnosti, vykonávat službu");
	pridejOtazku("perjury", "křivá přísaha");
	pridejOtazku("permanent residence", "trvalé bydliště");
	pridejOtazku("perpetrate crime", "páchat trestnou činnost");
	pridejOtazku("perpetrator", "pachatel");
	pridejOtazku("persist", "trvat");
	pridejOtazku("personal account", "osobní účet");
	pridejOtazku("personal responsibility", "osobní odpovědnost");
	pridejOtazku("personal use", "vlastní potřeba");
	pridejOtazku("personnel department", "osobní oddělení");
	pridejOtazku("a person of respectability", "respektovaná osoba, společností vážená osoba");
	pridejOtazku("perverting the course of justice", "maření soudního výkonu");
	pridejOtazku("petrol station", "benzínová čerpací stanice");
	pridejOtazku("petty crime, minor crime", "méně závažná trestná činnost, drobná kriminalita");
	pridejOtazku("pharmacy", "lékárna");
	pridejOtazku("phenomena", "jevy");
	pridejOtazku("phenomenon", "jev");
	pridejOtazku("phishing", "metody k odcizení digitální identity uživatele");
	pridejOtazku("phishing emails", "falešné kopie původních e-mailů");
	pridejOtazku("physical abuse", "týrání svěřené osoby");
	pridejOtazku("physical abuse", "fyzické napadání");
	pridejOtazku("pickpocketing", "kapesní krádeže");
	pridejOtazku("pill-taking", "brát prášky");
	pridejOtazku("plainclothes", "civilní oblečení");
	pridejOtazku("plea bargaining", "přiznání viny v některých bodech obžaloby");
	pridejOtazku("plead guilty", "přiznat vinu");
	pridejOtazku("plead guilty", "prohlášení o vině, přiznání viny");
	pridejOtazku("pliers", "kleště, kombinačky, kleště na drát");
	pridejOtazku("police", "policie, policejní sbor, policisté");
	pridejOtazku("Police Academy", "Policejní akademie");
	pridejOtazku("police authorities", "policejní orgány");
	pridejOtazku("police chief", "velitel policie");
	pridejOtazku("Police Chief Officer", "velitel");
	pridejOtazku("Police College", "vyšší policejní škola");
	pridejOtazku("police disciplinary procedure", "disciplinární řízení vedené s příslušníkem policie");
	pridejOtazku("police force", "policejní sbor");
	pridejOtazku("policing výkon", "policejní služby");
	pridejOtazku("policing", "policejní práce, výkon policejní činnosti, dohled, ochrana");
	pridejOtazku("policing", "výkon policejní činnosti");
	pridejOtazku("policymaker", "zákonodárce");
	pridejOtazku("political affiliation", "politická příslušnost");
	pridejOtazku("political conviction or religion", "politické přesvědčení či víra");
	pridejOtazku("portion", "část");
	pridejOtazku("pose", "vydávat se za koho");
	pridejOtazku("possessing", "držení, vlastnění, přechovávání");
	pridejOtazku("potential threats", "potenciální hrozby");
	pridejOtazku("powerful message", "jednoznačné, jasné poselství");
	pridejOtazku("precaution", "obezřetnost, opatření");
	pridejOtazku("precious", "cenný");
	pridejOtazku("predominantly", "převážně");
	pridejOtazku("prejudice", "předsudek, předpojatost");
	pridejOtazku("prejudice or hate", "předsudek či nenávist");
	pridejOtazku("prejudice somebody, something", "ovlivnit předsudky koho, způsobit u koho zaujetí");
	pridejOtazku("premeditated and cold-blooded killing", "úkladná, chladnoktevná vražda");
	pridejOtazku("premeditated criminal act", "úmyslný trsetný čin");
	pridejOtazku("premeditated intent", "úmyslný záměr");
	pridejOtazku("premises", "budova, provozovna");
	pridejOtazku("premises", "areál, komplex budov");
	pridejOtazku("present identification", "prokázat se");
	pridejOtazku("preservation of public tranquility", "ochrana veřejného pořádku");
	pridejOtazku("presidential seat", "sídlo presidenta");
	pridejOtazku("pretend", "předstírat");
	pridejOtazku("preventable", "vyhnutelný");
	pridejOtazku("prevent crime", "předcházet páchání trestné činnosti");
	pridejOtazku("prevention of crime", "prevence trestné činnosti");
	pridejOtazku("preventive custody", "vazba předstižná");
	pridejOtazku("principle", "zásada");
	pridejOtazku("prison sentence", "trest odnětí svobody");
	pridejOtazku("probation officer", "probační úředník");
	pridejOtazku("proceedings against a fugitive", "řízení proti uprchlému");
	pridejOtazku("proceedings against juveniles", "řízení proti mladistvým");
	pridejOtazku("proceeds", "zisk");
	pridejOtazku("produce a witness", "předvést svědka");
	pridejOtazku("profile of a police graduate", "profil absolventa policejní školy");
	pridejOtazku("profit", "zisk");
	pridejOtazku("prolific", "výkonný, úspěšný");
	pridejOtazku("prominent", "významný, hlavní");
	pridejOtazku("promote", "povýšit");
	pridejOtazku("promote", "podporovat");
	pridejOtazku("promotion from and within", "povýšení dle zákona o policii");
	pridejOtazku("prompt", "napovědět");
	pridejOtazku("proof", "důkaz");
	pridejOtazku("property", "majetek");
	pridejOtazku("property", "majetek, vlastnictví, jměmí");
	pridejOtazku("prosecute", "obžalovat, trestně stíhat");
	pridejOtazku("prosecution", "trestní řízení/stíhání");
	pridejOtazku("prosecution", "trestní stíhání");
	pridejOtazku("prosecution", "obžaloba, trestní / soudní stíhání");
	pridejOtazku("prosecutor", "státní zástupce");
	pridejOtazku("protection of life and property", "ochrana života a majetku");
	pridejOtazku("protect lives and property", "chránit životy a majetek");
	pridejOtazku("prove", "dokázat");
	pridejOtazku("provide", "poskytovat, zabezpečit");
	pridejOtazku("provide for", "zajišťovat");
	pridejOtazku("provide security", "zajišťovat bezpečnost");
	pridejOtazku("province", "obor, pole působnosti");
	pridejOtazku("provisional arrest", "předběžné zadržení");
	pridejOtazku("pry", "páčit, páčidlo");
	pridejOtazku("prying", "páčení");
	pridejOtazku("psychical abuse", "psychické týrání");
	pridejOtazku("psychotropic substances", "psychotropní látky");
	pridejOtazku("public corruption", "korupce veřejných činitelů");
	pridejOtazku("public entitie", "sveřejné instituce");
	pridejOtazku("public is excludeds", "vyloučením veřejnosti");
	pridejOtazku("public order", "veřejný pořádek");
	pridejOtazku("Public Order Police", "služba pořádkové policie");
	pridejOtazku("punch", "udeřit, dát ránu");
	pridejOtazku("punish", "potrestat, trestat");
	pridejOtazku("punish", "trestat");
	pridejOtazku("punishable", "podléhající trestu, trestně stíhatelný");
	pridejOtazku("punishment", "trest");
	pridejOtazku("purport", "zamýšlet");
	pridejOtazku("pursue", "stíhat, sledovat");
	pridejOtazku("put on probation", "odsoudit podmíněně");
	pridejOtazku("quash indictment", "stáhnout obžalobu");
	pridejOtazku("queries into", "dotazy");
	pridejOtazku("question", "vyslýchat");
	pridejOtazku("race", "rasa");
	pridejOtazku("racial and religious biases", "předsudky z rasisitických a náboženských pohnutek");
	pridejOtazku("racist", "rasistický, rasista");
	pridejOtazku("racketeer", "vyděrač");
	pridejOtazku("raid", "razie, zátah");
	pridejOtazku("rail network", "železniční síť");
	pridejOtazku("rank", "hodnost, služební zařazení");
	pridejOtazku("ransom", "výkupné");
	pridejOtazku("rape", "znásilnění, znásilnit");
	pridejOtazku("rape inquiry", "vyšetřování znásilnění");
	pridejOtazku("rapist", "pachatel znásilnění");
	pridejOtazku("rarely", "zřídka");
	pridejOtazku("rationale", "logický důvod, princip");
	pridejOtazku("reach", "dosáhnout, dostat se");
	pridejOtazku("reason", "důvod");
	pridejOtazku("recognize", "rozlišovat");
	pridejOtazku("recommendation", "doporučení");
	pridejOtazku("recommendation for punishment", "návrh na potrestání");
	pridejOtazku("record", "záznam");
	pridejOtazku("recover", "získat zpět");
	pridejOtazku("recovery", "zpětné získání");
	pridejOtazku("register", "evidence");
	pridejOtazku("regular", "remedy řádný opravný prostředek");
	pridejOtazku("relate to", "vztahovat se k");
	pridejOtazku("relayed through", "rozeslána");
	pridejOtazku("release", "propustit");
	pridejOtazku("reliable", "spolehlivý");
	pridejOtazku("reluctant", "neochotný");
	pridejOtazku("remain a danger", "představovat hrozbu");
	pridejOtazku("remain in custody", "být vězněn, být zbaven os svobody");
	pridejOtazku("remission", "prominutí, zmírnění trestu");
	pridejOtazku("remote control", "dálkový ovladač");
	pridejOtazku("render assistance", "poskytnout pomoc");
	pridejOtazku("repatriation of afflicted people", "repatriace postižených osob");
	pridejOtazku("report", "oznámit, nahlásit");
	pridejOtazku("reported crimes", "oznámené trestné činy");
	pridejOtazku("report to", "oznámit");
	pridejOtazku("report to the police", "oznámit policii");
	pridejOtazku("reputation", "pověst, renomé");
	pridejOtazku("requests", "požadavky");
	pridejOtazku("require", "vyžadovat, požadovat");
	pridejOtazku("required", "požadované");
	pridejOtazku("rescue", "osvobodit, zachránit");
	pridejOtazku("resentence to death", "potvrdit trest smrti");
	pridejOtazku("reserve", "vyhradit, zajistit");
	pridejOtazku("reside", "sídlit");
	pridejOtazku("residence alien", "cizinec s povolením k dlouhodobému pobytu");
	pridejOtazku("resist", "odolat");
	pridejOtazku("resources", "zdroje, prostředky");
	pridejOtazku("respond", "reagovat, odpovídat");
	pridejOtazku("respond", "reagovat");
	pridejOtazku("responsibilit", "zodpovědnost");
	pridejOtazku("responsible", "odpovědný");
	pridejOtazku("responsible for", "zodpovědný za");
	pridejOtazku("rest on", "spočívat na");
	pridejOtazku("retain", "podržet si, ponechat");
	pridejOtazku("retribution", "odplata");
	pridejOtazku("retry", "obnovit proces");
	pridejOtazku("ridge", "vyvýšenina, hřbet");
	pridejOtazku("risk analysis", "analýza rizik");
	pridejOtazku("road safety", "bezpečnost silničního provozu");
	pridejOtazku("road safety and flow of road traffic", "bezpečnost a plynulost silničního provozu");
	pridejOtazku("robbery", "loupež, vyloupení, oloupení");
	pridejOtazku("Romans", "Římané");
	pridejOtazku("route", "cesta, trasa");
	pridejOtazku("rule", "pravidlo, zásada");
	pridejOtazku("run anti-virus software", "spustit antivirový program");
	pridejOtazku("run the prison", "provozovat vězení");
	pridejOtazku("safe", "bezpečný");
	pridejOtazku("safety", "bezpečnostní");
	pridejOtazku("satisfy civil society's needs", "uspokojovat potřeby občanů");
	pridejOtazku("scene", "místo události");
	pridejOtazku("the scene of the crime, the crime scene", "místo činu");
	pridejOtazku("schedule", "naplánovat, rozvrhnout");
	pridejOtazku("scientifically", "vědecky");
	pridejOtazku("scratch", "škrábanec, škrábat");
	pridejOtazku("screwdriver", "šroubovák");
	pridejOtazku("search", "pátrání, pátrat");
	pridejOtazku("search", "hledat, pátrat, prohledávat, vykonávat osobní prohlídku");
	pridejOtazku("searches", "pátrání (více významů)");
	pridejOtazku("secluded", "spotodlehlé, opuštěné místo");
	pridejOtazku("Secretary General", "Generální tajemník");
	pridejOtazku("Secretary of State for the Home Department", "ministr vnitra");
	pridejOtazku("section", "paragraf");
	pridejOtazku("secure", "zajistit, ochránit");
	pridejOtazku("securities fraud", "podvody s cennými papíry");
	pridejOtazku("security", "bezpečnost");
	pridejOtazku("Security Information Service, (SIS)", "Bezpečnostní Informační Služba BIS");
	pridejOtazku("seek advice", "hledat, žádat o radu, pomoc");
	pridejOtazku("seek persons", "hledat osoby");
	pridejOtazku("seek the arrest", "vydat zatykač");
	pridejOtazku("seize", "zabavit");
	pridejOtazku("seizure", "zabavení");
	pridejOtazku("seldom", "zřídka");
	pridejOtazku("sell", "prodat");
	pridejOtazku("senior rank", "důstojnická hodnost");
	pridejOtazku("senior ranking officer", "služebně výše postavený policista");
	pridejOtazku("sentence", "soudit");
	pridejOtazku("sentence", "druh trestu");
	pridejOtazku("sentencing", "výrok rozsudku o trestu");
	pridejOtazku("sentencing", "ukládání trestů");
	pridejOtazku("serial murderer (killer)", "několikanásobný vrah");
	pridejOtazku("serious crime", "závažná trestná činnost, závažný trestný čin");
	pridejOtazku("seriously", "vážně");
	pridejOtazku("seriousness", "závažnost");
	pridejOtazku("serious offence", "závažný trestný čin");
	pridejOtazku("serious sexual offence", "závažný sexuální trestný čin");
	pridejOtazku("serve", "odpykávat si trest");
	pridejOtazku("serve citizens", "sloužit občanům");
	pridejOtazku("set of effective tools", "soubor efektivních nástrojů");
	pridejOtazku("severely", "přísně");
	pridejOtazku("sewn on", "našitý");
	pridejOtazku("sexual abuse", "sexuální zneužívání");
	pridejOtazku("sexual assault", "sexuální útok, napadení");
	pridejOtazku("sham", "předstíraný");
	pridejOtazku("shape", "ovlivňovat, utvářet, formovat");
	pridejOtazku("Sheriff's Office", "úřad šerifa");
	pridejOtazku("shift work", "práce na směny");
	pridejOtazku("shoplifting", "krádež v obchodě");
	pridejOtazku("shoulder surfing", "získání hesla (PIN) uživatele odpozorováním");
	pridejOtazku("sick leave", "nemocenská");
	pridejOtazku("side by side", "vedle sebe, společně");
	pridejOtazku("side window", "boční okénko");
	pridejOtazku("signs", "známky, stopy");
	pridejOtazku("single judge", "samosoudce");
	pridejOtazku("slice", "část");
	pridejOtazku("slip", "otevřít,odmknout");
	pridejOtazku("small amount", "malé množství");
	pridejOtazku("smash", "rozbít, zdemolovat, rozdrtit");
	pridejOtazku("smashed windows", "rozbitá okna");
	pridejOtazku("smash & grab", "rychlé rozbití skla a vykradení vozidla");
	pridejOtazku("smooth", "hladký");
	pridejOtazku("solicitor", "advokát, právník nižšího soudu");
	pridejOtazku("solve a crime", "vyřešit trestný čin");
	pridejOtazku("sophisticated", "rafinovaný");
	pridejOtazku("sound judgement", "zdravý úsudek");
	pridejOtazku("sound recording", "zvukový záznam");
	pridejOtazku("spate", "řada, série");
	pridejOtazku("special weapons and tactics team", "jednotka užívající speciální zbraně a taktiky");
	pridejOtazku("speeding", "překročení povolené rychlosti");
	pridejOtazku("spot", "rozeznat, zjistit");
	pridejOtazku("spousal abuse", "sexuální nátlak na partnera");
	pridejOtazku("spouse", "snoubenec, snoubenka, druh/žka, manžel/ka");
	pridejOtazku("stall-front selling", "stánkový prodej");
	pridejOtazku("statement of explanation", "podání vysvětlení");
	pridejOtazku("state police", "státní policie");
	pridejOtazku("State Prosecutor, Public Prosecutor", "státní zástupce");
	pridejOtazku("statistics", "statistika");
	pridejOtazku("steal", "dopuštět se krádeže, odcizit");
	pridejOtazku("steering wheel", "volant");
	pridejOtazku("steering wheel clamp", "zámek volantu");
	pridejOtazku("stipulate", "stanovit, určit");
	pridejOtazku("Stockholm syndrome", "stockholmský syndrom, vazba oběti na pachateli");
	pridejOtazku("street, drug-related, gun crime", "pouliční trestná činnost spojená s obchodováním s drogami, zbraněmi");
	pridejOtazku("strike ", "udeřit, narazit");
	pridejOtazku("struggle", "bojovat o co");
	pridejOtazku("struggle", "boj, potírání");
	pridejOtazku("subject to", "podléhající, vystavený čemu");
	pridejOtazku("subject to", "vystavit něčemu");
	pridejOtazku("submit", "předložit");
	pridejOtazku("submit a formal complaint", "předložit formální obvinění");
	pridejOtazku("substantial", "značný");
	pridejOtazku("suffer", "trpět, utrpět");
	pridejOtazku("suffer from", "trpět, strádat");
	pridejOtazku("suffering", "urtpení");
	pridejOtazku("summary offence", "trestný čin, který lze odsoudit sumárně");
	pridejOtazku("summary pre-trial proceedings", "zkrácené přípravné trestní řízení");
	pridejOtazku("summon", "předvolat");
	pridejOtazku("summons", "předvolání, obsílka");
	pridejOtazku("sum up the evidence", "shrnout důkazy");
	pridejOtazku("superhighway", "velmi rychlý způsob (jeden z významů)");
	pridejOtazku("supersede", "nahradit, odstranit");
	pridejOtazku("supervise", "dohlížet, kontrolovat, řídit");
	pridejOtazku("supervise", "dozorovat");
	pridejOtazku("supervise safety and the smoothness of traffic", "dohlížet nad bezpečností a plynulostí silničního provozu");
	pridejOtazku("supervision", "dohled, dozor");
	pridejOtazku("supervision order", "příkaz k dohledu probačním úředníkem");
	pridejOtazku("supply", "dodat, vybavit");
	pridejOtazku("suppressed", "evidence zatajené důkazy");
	pridejOtazku("supreme", "nejvyšší, vrchní, vrcholný");
	pridejOtazku("surface", "vyjít najevo");
	pridejOtazku("surveillance", "dohled, dozor (stálý)");
	pridejOtazku("surveillance", "sledování");
	pridejOtazku("survey", "přehled");
	pridejOtazku("susceptible to", "náchylný k");
	pridejOtazku("suspect", "podezřelý");
	pridejOtazku("suspended sentence", "podmíněné odsouzení, odložení výkonu trestu");
	pridejOtazku("suspicion", "podezření");
	pridejOtazku("suspicious", "podezřelý");
	pridejOtazku("suspicious activity", "podezřelá činnost");
	pridejOtazku("swear at", "používat hrubé výrazy");
	pridejOtazku("swirl", "kroužit");
	pridejOtazku("sworn officer", "policista pod přísahou");
	pridejOtazku("tackle", "bojovat proti, potírat co");
	pridejOtazku("tackle", "zvládnout");
	pridejOtazku("tackle", "vypořádat se");
	pridejOtazku("tag", "elektronicky monitorovat pomocí čipu");
	pridejOtazku("tagging", "elektronické monitorování pomocí čipu");
	pridejOtazku("take advantage of", "využít něčeho, těžit z");
	pridejOtazku("take a toll", "vybrat si daň");
	pridejOtazku("take into account", "vzít do úvahy, vzít v potaz, přihlédnout k čemu");
	pridejOtazku("take into consideration", "vzít v úvahu");
	pridejOtazku("take into custody", "vzít do vazby");
	pridejOtazku("tamper", "manipulovat, poškodit");
	pridejOtazku("target", "cíl, objekt");
	pridejOtazku("targets", "cíle");
	pridejOtazku("task force", "zvláštní jednotka");
	pridejOtazku("task force", "operační skupina, zásahová jednotka, komando");
	pridejOtazku("tax", "daň");
	pridejOtazku("tax", "evation daňový únik");
	pridejOtazku("tear", "rozpolcení, rozpolcenost1175. temptation pokušení");
	pridejOtazku("tempt fate", "pokoušet osud");
	pridejOtazku("term", "výraz");
	pridejOtazku("terrorism", "terorismus");
	pridejOtazku("testify", "vypovídat, ústně svědčit");
	pridejOtazku("testify in courts", "svědčit u soudů");
	pridejOtazku("theft", "krádež");
	pridejOtazku("theft of cash", "krádež peněz");
	pridejOtazku("thereafter", "potom, pak (knižně)");
	pridejOtazku("therein", "zde, v tomto ohledu");
	pridejOtazku("thievery", "krádež, zlodějství");
	pridejOtazku("threat", "hrozba");
	pridejOtazku("threaten", "ohrožovat, zastrašovat");
	pridejOtazku("threaten", "hrozit, ohrožovat");
	pridejOtazku("threaten the safety", "ohrozit bezpečnost");
	pridejOtazku("threats", "hrozby");
	pridejOtazku("threats", "pohrůžky");
	pridejOtazku("throw out", "zamítnout");
	pridejOtazku("tier", "úroveň, vrstva");
	pridejOtazku("tie up", "svázat");
	pridejOtazku("tip", "špička");
	pridejOtazku("to abuse", "zneužívat");
	pridejOtazku("to ail", "bolet, trápit, sužovat");
	pridejOtazku("to be appointed by", "být jmenován kým . . .");
	pridejOtazku("to be ashamed", "být zahanben");
	pridejOtazku("to be sacked", "být propuštěn");
	pridejOtazku("to combat", "bojovat proti, potírat co");
	pridejOtazku("tolerance for drugs", "snášenlivost léku, drogy, tolerance na drogu");
	pridejOtazku("tool", "nástroj");
	pridejOtazku("toolmark", "stopa, způsobená nástrojem");
	pridejOtazku("to prevent", "předejít, zabránit");
	pridejOtazku("torture", "mučení, mučit");
	pridejOtazku("torture", "mučení, týrání");
	pridejOtazku("toughened safety glass", "tvrzené sklo, bezpečnostní sklo");
	pridejOtazku("tougher penalties", "tvrdší, přísnější tresty");
	pridejOtazku("township", "správní oblast, okres");
	pridejOtazku("track", "sledovat");
	pridejOtazku("track down", "vystopovat");
	pridejOtazku("traffic", "provoz, ruch");
	pridejOtazku("trafficking", "nedovolené, nezákonné obchodování, kšeftování");
	pridejOtazku("traffic monitoring", "monitorování dopravy");
	pridejOtazku("Traffic Police", "služba dopravní policie");
	pridejOtazku("traffic warden", "příslušník služby dopravní policie, dopravní policista");
	pridejOtazku("train ", "provádět výcvik a školit");
	pridejOtazku("Training Center", "výcvikové centrum");
	pridejOtazku("transfer", "postoupit");
	pridejOtazku("transgender people", "transsexuálové");
	pridejOtazku("transponder key", "klíč se zabudovaným čipem");
	pridejOtazku("travel documents", "cestovní doklady");
	pridejOtazku("treason", "vlastizrada, velezrada");
	pridejOtazku("Treasury Department", "Ministerstvo financí");
	pridejOtazku("treatment", "terapie, léčba");
	pridejOtazku("trespass", "neoprávněné vniknutí");
	pridejOtazku("trespass", "přečin, proviění");
	pridejOtazku("triable either way offence", "strestné činy, které lze projednávat u nižšího i vyššího soudu");
	pridejOtazku("trial", "hlavní líčení");
	pridejOtazku("tribal", "kmenový");
	pridejOtazku("trick", "podvést,klamat");
	pridejOtazku("tripartite relationship", "třístranné vztahy");
	pridejOtazku("trooper", "policista");
	pridejOtazku("turnig", "otáčení");
	pridejOtazku("ultimate denial of human rights", "absolutní popření lidských práv");
	pridejOtazku("unauthorized", "neoprávněný");
	pridejOtazku("unconditional discharge", "bezpodmíněné propuštění");
	pridejOtazku("undercover", "tajný");
	pridejOtazku("underestimate", "podcenit");
	pridejOtazku("underhand", "podvodný, lstivý");
	pridejOtazku("underlying", "základní");
	pridejOtazku("underlying", "být zásadním prvkem (jeden z významů)");
	pridejOtazku("under the guis", "pod rouškou");
	pridejOtazku("undisturbed", "neporušený");
	pridejOtazku("unfounded and malicious complaints", "neopodstatněné a zlomyslné stížnosti");
	pridejOtazku("unidentified bodies", "mrtvoly neznámé totožnosti");
	pridejOtazku("uniformed police officers", "uniformovaní policisté");
	pridejOtazku("unique", "jedinečný");
	pridejOtazku("unique password", "vlastní heslo, které zná pouze uživatel");
	pridejOtazku("the Universal Declaration of Human Rights", "Všeobecná deklarace lidských práv");
	pridejOtazku("unlawful assembly", "nedovolené shromažďování");
	pridejOtazku("unsolved crimes", "nevyřešené trestné činy");
	pridejOtazku("unvillingness", "neochota");
	pridejOtazku("unwilling users", "nedobrovolní uživatelé");
	pridejOtazku("upgrading", "vylepšení, inovace");
	pridejOtazku("uphill battle", "obtížný boj");
	pridejOtazku("urban", "městský");
	pridejOtazku("users", "uživatelé");
	pridejOtazku("utility bills", "účty za služby domácnostem (elek,plyn, voda ...)");
	pridejOtazku("validate", "potvrdit (platnost), ověřit");
	pridejOtazku("value", "hodnota, cena");
	pridejOtazku("vandalised cars", "zničené automobily");
	pridejOtazku("vandalism", "vandalství, záměrné pustošení, vandalismus");
	pridejOtazku("variety", "velký počet,mnoho");
	pridejOtazku("vary by jurisdiction", "lišit se podle jurisdikce");
	pridejOtazku("varying", "rozličný, proměnlivý");
	pridejOtazku("vast", "obrovský,ohromný");
	pridejOtazku("verbal abuse", "verbální napadání");
	pridejOtazku("verbal taunts", "verbální narážky, posměch");
	pridejOtazku("verification", "procedureprověřování");
	pridejOtazku("verify", "prověřit");
	pridejOtazku("vetting", "prověřování (vhodnosti)");
	pridejOtazku("victim", "poškozený, oběť");
	pridejOtazku("victimized partner", "partner poškozený trestným činem");
	pridejOtazku("violate law", "porušit zákon");
	pridejOtazku("violate the rights", "porušovat práva");
	pridejOtazku("violation of trust", "zneužití funkce");
	pridejOtazku("violence", "násilí");
	pridejOtazku("violence against a group of inhabitants and individuals", "násilí proti skupině obyvatel a proti jednotlivci");
	pridejOtazku("violent", "násilný");
	pridejOtazku("violent crime", "násilná trestná činnost, násilný trestný čin");
	pridejOtazku("vitiate the civility", "narušit civilizované chování");
	pridejOtazku("voluntary manslaughter", "vražda, zabití");
	pridejOtazku("walk the beat", "provádět pěší obchůzku");
	pridejOtazku("a wanted person", "hledaná osoba");
	pridejOtazku("war crimes", "válečné zločiny");
	pridejOtazku("warehouse", "skladiště");
	pridejOtazku("warn", "varovat");
	pridejOtazku("warning", "varování");
	pridejOtazku("wave", "vlna");
	pridejOtazku("weapons smuggling", "pašování zbraní");
	pridejOtazku("weep", "plakat");
	pridejOtazku("welfare", "sociální jistota, sociální stát");
	pridejOtazku("wherein", "kde, v kterém");
	pridejOtazku("white-collar crime", "trestní čin úředníkem, prac v administrativě, krim bílých límečků");
	pridejOtazku("white-collar crime", "kriminalita \"bílých límečků\", hospodářská tresná činnost");
	pridejOtazku("white-collar crime", "trestná tzv. \"bílých límečků\", hospodářská trestná činnost");
	pridejOtazku("white neighbourhoods", "čtvrti obydlené bělochy");
	pridejOtazku("whorl", "rýha");
	pridejOtazku("windscreen", "čelní sklo");
	pridejOtazku("with a view to", "s možností");
	pridejOtazku("withdrawal", "výběr peněz z účtu");
	pridejOtazku("with the intent to", "s úmyslem");
	pridejOtazku("witness", "svědek");
	pridejOtazku("witness", "být svědkem");
	pridejOtazku("work on foot", "hlídkovat, vykonávat pochůzky");
	pridejOtazku("world history", "světové dějiny");
	pridejOtazku("worth", "mající hodnotu");
	pridejOtazku("worthless", "bezcenný");
	pridejOtazku("write a report", "vypracovat, sepsat úřední záznam");
	pridejOtazku("writing document", "listinný dokumen");



}

function pridejOtazku(otazka, odpoved) {
	var q = {
		otazka: otazka,
		odpoved: odpoved
	};

	otazky.push(q);
}