var n = 0;
var otazky = new Array();
var spatneOtazky = new Array();
var odpovezene = new Array();

var spravne = 0;
var spatne = 0;

var otazka;

var x = 0;

function start() {
	zalozOtazky();
	document.getElementById('start').remove();

	document.getElementById('otazka').style.visibility = 'visible';
	//document.getElementById('odpoved').style.visibility = 'visible';
	document.getElementById('check').style.visibility = 'visible';
	document.getElementById('otazkaCislo').style.visibility = 'visible';

	nactiOtazku();
}

function nactiOtazku() {
	if (otazky.length <= n) {
		document.getElementById("form").style.visibility = 'hidden';
		document.getElementById("otazkaCislo").style.visibility = 'hidden';
		document.getElementById("dalsi").style.visibility = 'hidden';

		document.getElementById("check").innerHTML = '<p>Správných odpovědí: ' + spravne + '</p>' +
			'<p>Špatných odpovědí: ' + spatne + '</p>' +
			'<button id="spatneOtazky" type="button" onclick=nactiSpatne()>Znovu špatné otázky</button>';
		return;
	}

	while (true) {
		x = Math.floor((Math.random() * otazky.length));
		if (odpovezene.indexOf(x) >= 0)
			;
		else
			break;
	}

	document.getElementById('otazkaCislo').innerHTML = "Otázka " + (n + 1) + " z " + (otazky.length);
	document.getElementById("check").style.visibility = 'hidden';
	document.getElementById("dalsi").style.visibility = 'hidden';
	otazka = otazky[x];
	document.getElementById('otazka').innerHTML = '<div id="form">' +
		otazka.otazka + ': <br><input id="id1" type="text" name="question" onkeypress="isEnter()">' +
		'<input id="end" type="button" value="Odpovědět" onclick=check()>' +
		'</div>';

	document.getElementById("id1").focus();
}

function nactiSpatne() {
	document.getElementById("form").style.visibility = 'visible';
	document.getElementById("otazkaCislo").style.visibility = 'visible';
	document.getElementById("dalsi").style.visibility = 'visible';
	document.getElementById('otazka').style.visibility = 'visible';
	document.getElementById('check').style.visibility = 'visible';

	otazky = [];
	otazky = spatneOtazky;
	spatneOtazky = [];
	n = 0;
	x = 0;
	spravne = 0;
	spatne = 0;
	odpovezene = [];
	nactiOtazku();
}

function isEnter(e) {
	if ((event.which == 13 || event.keyCode == 13)) {
		if (document.getElementById("dalsi").style.visibility == 'visible') {
			nactiOtazku();
		} else {
			check();
		}
	}
}

function check() {
	//document.getElementById("check").innerHTML = document.getElementById("id1").value;
	document.getElementById("check").style.visibility = 'visible';
	if (document.getElementById("id1").value == otazka.odpoved) {
		document.getElementById("check").innerHTML = '<p style="color:green">Správná odpověď</p>';
		spravne++;
	} else {
		document.getElementById("check").innerHTML = '<p style="color:red">Špatně!</p>' +
			'Správná odpověď je: ' + otazka.odpoved;
		spatne++;
		spatneOtazky.push(otazka)
	}

	if (otazky.length > n) {
		odpovezene.push(x);
		n++;

		document.getElementById("end").style.visibility = 'hidden';
		document.getElementById("dalsi").style.visibility = 'visible';
	}
	/*else{
	 document.getElementById("form").remove();
	 document.getElementById("otazkaCislo").remove();;
	 document.getElementById("check").innerHTML = '<p>Správných odpovědí: ' + spravne + '</p>' + 
	 '<p>Špatných odpovědí: ' + spatne + '</p>'
	 }*/
}

function zalozOtazky() {
	pridejOtazku("unést", "abduct");
	pridejOtazku("únos např. dítěte", "abduction");
	pridejOtazku("únosce", "abductor");
	pridejOtazku("zrušit", "abolish");
	pridejOtazku("zrušení", "abolishment");
	pridejOtazku("země, které zrušily trest smrti", "abolitionist");
	pridejOtazku("zneužívat, týrat, zneužívání, týrání", "abuse");
	pridejOtazku("zneužití", "abuse");
	pridejOtazku("zneužití, zneužívat", "abuse");
	pridejOtazku("urážka, nadávka", "abuse");
	pridejOtazku("zneužití pravomoci veřejného činitele", "abuse of public official powers");
	pridejOtazku("dopouštět se fyzického násilí", "abuse physically");
	pridejOtazku("přístup", "access");
	pridejOtazku("dostupný", "accessible");
	pridejOtazku("vstup", "accession");
	pridejOtazku("náhodný", "accidental");
	pridejOtazku("oběť nehody", "accident victim");
	pridejOtazku("bankovní účet", "account");
	pridejOtazku("účet", "account");
	pridejOtazku("zprostit viny", "acquit");
	pridejOtazku("zákon", "Act");
	pridejOtazku("čin, jednání, zákon", "act");
	pridejOtazku("lehké ublížení na zdraví", "actual bodily harm");
	pridejOtazku("návyk, sklon, závislost", "addiction");
	pridejOtazku("doplňkový", "additional");
	pridejOtazku("dávat jako součet, znamenat", "add up");
	pridejOtazku("nastavit, přizpůsobit", "adjust");
	pridejOtazku("přijmout", "adopt");
	pridejOtazku("pokrok", "advance");
	pridejOtazku("poradce", "adviser");
	pridejOtazku("otázka, záležitost, věc", "affair");
	pridejOtazku("přitěžující okolnost", "aggravating circumstance");
	pridejOtazku("zaměřit se na", "aim at");
	pridejOtazku("usilovat o co", "aim to");
	pridejOtazku("letecká záchranná služba", "Air Rescue Service");
	pridejOtazku("poplašné zařízení", "alarm");
	pridejOtazku("ostražitý, ve střehu, ve stavu pohotovosti", "alert");
	pridejOtazku("falešné jméno, přezdívka", "alias");
	pridejOtazku("cizinec", "alien");
	pridejOtazku("služba pohraniční a cizinecké policie", "Alien Police");
	pridejOtazku("obvinění z údajného trestného činu", "allegation");
	pridejOtazku("údajný", "alleged");
	pridejOtazku("údajný, domnělý", "alleged");
	pridejOtazku("přijmout nebo zamítnout odvolání", "allow or dismiss the appeal");
	pridejOtazku("dodatek", "amendment");
	pridejOtazku("ročně, každoročně", "annually");
	pridejOtazku("anonymně", "anonymously");
	pridejOtazku("odpovědný", "answerable");
	pridejOtazku("program pro zabezpečení PC proti proniknutí", "anti-spyware software");
	pridejOtazku("žádost o", "applications for");
	pridejOtazku("jmenovat", "appoint");
	pridejOtazku("jmenování (do funkce, hodnosti)", "appointment");
	pridejOtazku("zadržet", "apprehend");
	pridejOtazku("zatknout", "apprehend");
	pridejOtazku("zadržení", "apprehension");
	pridejOtazku("vzetí do vazby", "apprehension of");
	pridejOtazku("přivlastnit si", "appropriate");
	pridejOtazku("náležitě", "appropriately");
	pridejOtazku("schválit", "approve");
	pridejOtazku("považovat za správné", "approve of");
	pridejOtazku("příkaz k zatčení, zatykač", "arest warrant");
	pridejOtazku("ozbrojený", "armed");
	pridejOtazku("Arméni", "Armenians");
	pridejOtazku("24 hodin denně", "around the clock");
	pridejOtazku("zatčení, zajištění, zadržení", "arrest");
	pridejOtazku("žhářství", "arson");
	pridejOtazku("uměle vyhnat cenu nahoru", "artificially inflate the price");
	pridejOtazku("zjistit", "ascertain");
	pridejOtazku("útočník, násilník", "assailant");
	pridejOtazku("napadení, přepadení, útok", "assault");
	pridejOtazku("útok, napadení", "assault");
	pridejOtazku("napadení veřejného činitele", "assaulting a public official");
	pridejOtazku("napadení koho, útok na", "assault on");
	pridejOtazku("přidělit k", "assign to");
	pridejOtazku("zástupce ředitele ředitelství policie", "Assistant Inspector of Constabulary");
	pridejOtazku("přijmout, vzít na sebe", "assume");
	pridejOtazku("předpoklad", "assumption");
	pridejOtazku("na svobodě", "at large");
	pridejOtazku("pokusit se, pokus", "attempt");
	pridejOtazku("pokus trestného činu", "attempted offence");
	pridejOtazku("pokus o znásilnění", "attempted rape");
	pridejOtazku("pokus o útěk", "attempt to escape");
	pridejOtazku("v samé podstatě svobodné společnosti", "at the very fabric of free society");
	pridejOtazku("úřady", "authorities");
	pridejOtazku("k dispozici", "available");
	pridejOtazku("vyhnout se, vyvarovat se", "avoid");
	pridejOtazku("bakalářský stupeň studia", "Bachelor Degree");
	pridejOtazku("odznak", "badge");
	pridejOtazku("kauce", "bail");
	pridejOtazku("soudní zřízenec", "bailiff");
	pridejOtazku("bankovní loupež", "bank robbery");
	pridejOtazku("spojené s vyhlašováním konkurzu", "bankruptcy fraudpodvody");
	pridejOtazku("výpis z účtu", "bank statement");
	pridejOtazku("násilník", "batterer");
	pridejOtazku("ublížení na zdraví, fyzické napadení, použití násilí proti osobě", "battery");
	pridejOtazku("ublížení na zdraví", "battery");
	pridejOtazku("být řešen čím", "be addressed through");
	pridejOtazku("být varován, být upozorněn na", "be alerted to");
	pridejOtazku("opatřit značkou, logem", "bear the name");
	pridejOtazku("být na svobodě", "be at large");
	pridejOtazku("být si vědom čeho", "be aware of something");
	pridejOtazku("kvůli, z důvodu, vzhledem k", "because of");
	pridejOtazku("smít svěřeny pravomoci", "be entrusted with power");
	pridejOtazku("být zapojen do, angažovaný v, zúčastněný v", "be involved in");
	pridejOtazku("víra, přesvědčení", "belief");
	pridejOtazku(" být v podmínce, na svobodě při podmíněném prominutí trestu", "be on probation");
	pridejOtazku(" být personálně obsazen", "be staffed by");
	pridejOtazku("podléhat čemu", "be subject to");
	pridejOtazku("nad vší pochybnost", "beyond any reasonable doubt");
	pridejOtazku("trestná činnost související s předsudky, předpojatostí", "bias related crime");
	pridejOtazku("bilaterální, dvoustranná dohoda", "bilateral agreement");
	pridejOtazku("miliarda", "billion");
	pridejOtazku("material takingodběr biologického materiálu", "biological");
	pridejOtazku("vydírání, vyděračství", "blackmail");
	pridejOtazku("čepel", "blade");
	pridejOtazku("očividný, výrazný, zřejmý, jednoznačný", "blatant, obvious");
	pridejOtazku("krevní zkouška", "blood test");
	pridejOtazku("rada, výbor", "board");
	pridejOtazku("orgány", "bodies");
	pridejOtazku("padělaný, nepravý, falešný", "bogus");
	pridejOtazku("západka, zástrčka", "bolt");
	pridejOtazku("disposal zneškodňování výbušnin", "bomb");
	pridejOtazku("hranice", "border");
	pridejOtazku("hraniční kontroly", "border checks");
	pridejOtazku("pohraniční kontrola", "border control");
	pridejOtazku("bezpečnostna hranicích", "border security");
	pridejOtazku("provedené vyšetřování", "botched investigationnedbale");
	pridejOtazku("porouchat se", "break");
	pridejOtazku("vloupání", "break in");
	pridejOtazku("porušit zákon", "break the law");
	pridejOtazku("uplácení", "bribery");
	pridejOtazku("předvést", "bring");
	pridejOtazku("šikanování", "bullying");
	pridejOtazku("vloupání", "burglary");
	pridejOtazku("vyzvat, žádat", "call for");
	pridejOtazku("psovodi", "canine corps");
	pridejOtazku("trestné činy, za něž je možné uložit trest smrti", "capital crimes");
	pridejOtazku("trest smrti", "capital punishment");
	pridejOtazku("trest smrti", "capital punishment, death penalty, death sentence");
	pridejOtazku("sídlo vlády", "capitol parlament");
	pridejOtazku("ochranná služba", "capitol police");
	pridejOtazku("zbavení osobní svobody, omezování os svobody", "captivity");
	pridejOtazku("zavazadlový prostor vozidla", "car boot");
	pridejOtazku("prodej z kufru auta", "car boot sale");
	pridejOtazku("únos (auta)", "carjacking");
	pridejOtazku("být řádně označen", "carry due identification");
	pridejOtazku("provádět expertízu, vypracovat odborné posudky", "carry out expertise");
	pridejOtazku("hotovost", "cash");
	pridejOtazku("přistihnout", "catch out");
	pridejOtazku("zapřičinit, způsobit", "cause");
	pridejOtazku("příčina", "cause");
	pridejOtazku("silnice vedená po hrázi", "causeway");
	pridejOtazku("obezřetnost, opatrnost", "caution");
	pridejOtazku("zastavit", "cease");
	pridejOtazku("centrální vláda", "central government");
	pridejOtazku("náročný, podnětný, představující výzvu", "challenging");
	pridejOtazku("obvinění, obžaloba", "charge");
	pridejOtazku("obvinit něhoho z", "charge somebody with");
	pridejOtazku("obvinit z", "charge with");
	pridejOtazku("obsahující, popisující", "charting");
	pridejOtazku("kontrolovat, zkontrolovat", "check");
	pridejOtazku("britská lékárna", "chemist's");
	pridejOtazku("zneužívání dítěte", "child abuse");
	pridejOtazku("zanedbání povinné výživy, výchovy", "child neglect");
	pridejOtazku("dětská pornografie", "child pornography");
	pridejOtazku("křesťané", "Christians");
	pridejOtazku("okolnost", "circumstance");
	pridejOtazku("předvolání, obsílka", "citation");
	pridejOtazku("občansko právní kolegium", "Civil Division");
	pridejOtazku("občansko právní řízení", "civil proceedings");
	pridejOtazku("občanští, civilní zaměstnanci", "civil support staff");
	pridejOtazku("tvrzení", "claim");
	pridejOtazku("žádost, požadavek", "claim");
	pridejOtazku("objasnění", "clarification");
	pridejOtazku("hromažďovat doplňující informace", "collect additional informations");
	pridejOtazku("evidence získávat, shromažďovat důkazy", "collect");
	pridejOtazku("vyšetřování", "collection");
	pridejOtazku("boj, potírání", "combat");
	pridejOtazku("bojovat", "combat");
	pridejOtazku("bojovat s trestnou činností", "combat crime");
	pridejOtazku("velení", "command");
	pridejOtazku("zahájení trestního stíhání", "commencing the act");
	pridejOtazku("spáchat", "commit");
	pridejOtazku("spáchat trestný čin", "commit a crime");
	pridejOtazku("páchat trestnou činnost", "commit crime");
	pridejOtazku("páchat, dopustit se trestných činů", "commit criminal acts");
	pridejOtazku("předat soudu", "commit somebody to the court");
	pridejOtazku("spáchat sebevraždu", "commit suicide");
	pridejOtazku("řízení ve věci", "committal proceeding");
	pridejOtazku("výbor, komise", "committee");
	pridejOtazku("podvody s komoditami", "commodities fraud");
	pridejOtazku("obvyklý, běžný, společný", "common");
	pridejOtazku("fyzické napadení", "common assault");
	pridejOtazku("komunikativní dovednosti", "communication skills");
	pridejOtazku("orgán společenství", "community body");
	pridejOtazku("policej. činnost ve spolupráci s míst. obyvatelstvem (jako kdysi četnictvo)", "community policing");
	pridejOtazku("veřejně prospěšné práce", "community service");
	pridejOtazku("stížnost", "complaint");
	pridejOtazku("stížnost pro porušení zákona", "complaint for breaching the law");
	pridejOtazku("počítačová kriminalita", "computer crime");
	pridejOtazku("notorický podvodník", "con artist");
	pridejOtazku("utajování", "concealment");
	pridejOtazku("pojem", "concept");
	pridejOtazku("znepokojení", "concern");
	pridejOtazku("zajímat se", "concern");
	pridejOtazku("závěry", "conclusions");
	pridejOtazku("podmíněné zastavení trestního stíhání", "conditional cessation of prosecution");
	pridejOtazku("podmíněné propuštění", "conditional discharge");
	pridejOtazku("podmíněně", "conditionally");
	pridejOtazku("provádět, vést, řídit", "conduct");
	pridejOtazku("důvěra", "confidence");
	pridejOtazku("zabavit", "confiscate");
	pridejOtazku("odpovídat čemu", "conform to");
	pridejOtazku("nepřetržitý, po sobě jdoucí", "consecutive");
	pridejOtazku("následek", "consequence");
	pridejOtazku("považovat", "consider");
	pridejOtazku("strážník, policista", "constable");
	pridejOtazku("ředitelství policie", "constabulary");
	pridejOtazku("neustále ve stavu pohotovosti, ve střehu", "constantly alert");
	pridejOtazku("zakládat trestný čin", "constitute a criminal offence");
	pridejOtazku("zakládat důvod", "constitute a reason");
	pridejOtazku("ústavní činitel", "constitutional official");
	pridejOtazku("poškozování spotřebitele", "consumer fraud");
	pridejOtazku("pohrdání soudem", "contempt of court");
	pridejOtazku("kontinuální vzdělávání, soustavné sebevzdělávání", "continuous self education");
	pridejOtazku("linie, obrys, tvar", "contour");
	pridejOtazku("odsoudit, usvědčit, uznat/shledat vinným", "convict");
	pridejOtazku("odsoudit, odsouzený", "convict, convicted");
	pridejOtazku("odsouzený", "convicted");
	pridejOtazku("usvědčení, rozsudek", "conviction");
	pridejOtazku("výrok o vině", "conviction");
	pridejOtazku("odsouzení", "conviction");
	pridejOtazku("konstatovat vinu", "convict of");
	pridejOtazku("odsoudit za trestný čin", "convict of a crime");
	pridejOtazku("spolupracovat", "cooperate");
	pridejOtazku("porušování autorského práva", "copyright theft");
	pridejOtazku("ovládnout", "corner");
	pridejOtazku("úřední ohledavač mrtvol", "coroner");
	pridejOtazku("firemní nepoctivost", "corporate dishonesty");
	pridejOtazku("firemní podvody", "corporate fraud");
	pridejOtazku("korupce", "corruption");
	pridejOtazku("náklady, cena", "cost");
	pridejOtazku("syrup sirup proti kašli", "cough");
	pridejOtazku("obhájce", "counsel");
	pridejOtazku("padělaný", "counterfeit");
	pridejOtazku("padělat", "counterfeit");
	pridejOtazku("padělání", "counterfeiting");
	pridejOtazku("správní oblast, okres v rámci jednotlivých států USA", "county");
	pridejOtazku("soud", "court");
	pridejOtazku("odvolací soud", "court of appeal");
	pridejOtazku("soud", "court of trial");
	pridejOtazku("policejní zásah, zákrok", "crackdown");
	pridejOtazku("zásah, zákrok", "crackdown");
	pridejOtazku("rozbít, havarovat", "crash");
	pridejOtazku("vytvářet", "create");
	pridejOtazku("důvěryhodnost", "credibility");
	pridejOtazku("důvěryhodný, věrohodný, spolehlivý", "credible");
	pridejOtazku("úvěrová karta", "credit card");
	pridejOtazku("podvody s kreditními kartami", "credit card frauds");
	pridejOtazku("přesvědčení, vyznání", "creed");
	pridejOtazku("trestný čin, zločin", "crime");
	pridejOtazku("prevence kriminality", "crime prevention");
	pridejOtazku("míra kriminality, nápad trestné činnosti", "crime rate");
	pridejOtazku("registr trestné činnosti", "crime registry");
	pridejOtazku("informace, týkající se trestné činnosti", "crime-related information");
	pridejOtazku("zločiny proti lidskosti", "crimes against humanity");
	pridejOtazku("trestné činy proti majetku", "crimes against property");
	pridejOtazku("místo činu", "crime scene");
	pridejOtazku("místo trestného činu", "crime scene");
	pridejOtazku("série trestných činů", "crime spree");
	pridejOtazku("kriminalita, trestná činnost", "crime");
	pridejOtazku("pachatel trestného činu", "criminal");
	pridejOtazku("služba kriminální policie a vyšetřování", "Criminal and Investigation Police");
	pridejOtazku("trestní případy", "criminal cases");
	pridejOtazku("trestní zákon", "Criminal Code");
	pridejOtazku("zločinné spiknutí", "criminal conspiracy");
	pridejOtazku("trestní příkaz", "criminal court order");
	pridejOtazku("trestní kolegium", "Criminal Division");
	pridejOtazku("informace, týkající se trestné činnosti", "criminal intelligence");
	pridejOtazku("kriminalistická laboratoř", "criminalistics laboratory");
	pridejOtazku("trestný čin", "criminal offence");
	pridejOtazku("trestné činy", "criminal offences");
	pridejOtazku("služba kriminální policie a vyšetřování", "Criminal Police and Investigation Department");
	pridejOtazku("trestní řád", "Criminal Procedure Code");
	pridejOtazku("trestní řízení/stíhání", "criminal proceedings");
	pridejOtazku("přeshraniční", "cross-border");
	pridejOtazku("pálení křížů", "cross burnings");
	pridejOtazku("královský soud", "Crown Court");
	pridejOtazku("rozhodující, klíčový", "crucial");
	pridejOtazku("zvláště trýznivý", "cruel");
	pridejOtazku("zvláště trýznivým způsobem", "cruelly");
	pridejOtazku("mučivé útrapy", "cruelty");
	pridejOtazku("omezit", "curb");
	pridejOtazku("vazba", "custody");
	pridejOtazku("návrh na uvalení vazby", "custody petition");
	pridejOtazku("celní správa", "customs");
	pridejOtazku("celní kontrola", "customs control");
	pridejOtazku("daktyloskopická stopa", "dactyloscopic print");
	pridejOtazku("ztráta", "damage");
	pridejOtazku("škoda, újma, poškození", "damage");
	pridejOtazku("znásilnění mezi partnery ne v manželském svazku", "date rape");
	pridejOtazku("bezpečnostní zámek", "deadbolt");
	pridejOtazku("prodej", "dealing");
	pridejOtazku("zabývat se, jednat", "deal with");
	pridejOtazku("zabývat se něčím, projednávat co", "deal with");
	pridejOtazku("zvládnout, vypořádat se", "deal with");
	pridejOtazku("řešit, zabývat se", "deal with");
	pridejOtazku("úmrtí", "death");
	pridejOtazku("trest smrti", "death penalty");
	pridejOtazku("trest smrti", "death sentence");
	pridejOtazku("podvod, klam", "deceit");
	pridejOtazku("podvod, klam, trik, podvod s totožností", "deception");
	pridejOtazku("obžalovaný", "defendant");
	pridejOtazku("obviněný, obžalovaný", "defendant");
	pridejOtazku("úcta, ohled", "deference");
	pridejOtazku("definovat, psát", "define");
	pridejOtazku("oklamat, ošidit", "defraud");
	pridejOtazku("stupeň", "degree");
	pridejOtazku("úmyslný", "deliberate");
	pridejOtazku("delikvence, kriminalita, zločinnost", "delinquency");
	pridejOtazku("požadovat", "demand");
	pridejOtazku("požadovat vysvětlení", "demand a testimony");
	pridejOtazku("požadovat prokázání totožnosti", "demand personal identification");
	pridejOtazku("oddělení", "department");
	pridejOtazku("závislost", "dependency");
	pridejOtazku("uložit, vklad", "deposit");
	pridejOtazku("zástupce", "deputy");
	pridejOtazku("náměstek, zástupce", "deputy");
	pridejOtazku("zástupce šerifa", "deputy sheriff");
	pridejOtazku("určené kontaktní místo", "designated contact point");
	pridejOtazku("odloučené pracoviště", "detachment");
	pridejOtazku("zajistit", "detain");
	pridejOtazku("dopadnout, vypátrat", "detect");
	pridejOtazku("objevit, zjistit", "detect");
	pridejOtazku("zjišťovat, odhalovat", "detect");
	pridejOtazku("vypátrání pachatelů", "detection of offenders");
	pridejOtazku("zabránit", "deter");
	pridejOtazku("odstrašit, odradit", "deter");
	pridejOtazku("určit, stanovit, rozhodnout", "determine");
	pridejOtazku("určit", "determine");
	pridejOtazku("určit, stanovit", "determine");
	pridejOtazku("stanovit, určit", "determine");
	pridejOtazku("odrazující", "deterrent");
	pridejOtazku("odstrašující prostředek", "deterrent");
	pridejOtazku("zařízení, přístroj", "device");
	pridejOtazku("postoupit", "devolve");
	pridejOtazku("odlišná úroveň", "different level");
	pridejOtazku("bezprostřední nebezpečí závažného zranění nebo smrti", "direct danger of severe injury or death");
	pridejOtazku("místo neštěstí, katastrofy", "disaster scene");
	pridejOtazku("přerušit", "discontinue");
	pridejOtazku("skryté zbraně", "disguised weapons");
	pridejOtazku("zamítnout", "dismiss");
	pridejOtazku("spor, hádka", "dispute");
	pridejOtazku("rozlišit, rozeznávat", "distinguish");
	pridejOtazku("rozptýlit, vyrušit, obrátit pozornost", "distract");
	pridejOtazku("správní oblast, obvod, okres", "district");
	pridejOtazku("porušit", "disturb");
	pridejOtazku("narušování veřejného pořádku", "disturbing the peace");
	pridejOtazku("různý, rozličný", "diverse");
	pridejOtazku("doktorský stupeň studia", "Doctor Degree");
	pridejOtazku("shromažďování dokumentace", "documentation gathering");
	pridejOtazku("týrání svěřené osoby", "domestic abuse");
	pridejOtazku("domácí násilí", "domestic violence");
	pridejOtazku("dávka", "dose");
	pridejOtazku("pochybovat", "doubt");
	pridejOtazku("návrh", "draft");
	pridejOtazku("odvést z, vyvést z", "drive from");
	pridejOtazku("porušení pravidel silničního provozu", "driving offence");
	pridejOtazku("americká lékárna", "drug store");
	pridejOtazku("nekalé obchodování s drogami", "drug trafficking");
	pridejOtazku("opilost a výtržnictví", "drunk and disorderly");
	pridejOtazku("vysypávání odpadků", "dumping of rubbish");
	pridejOtazku("probírání se odpadky (v průmyslové špionáži)", "dumpster diving");
	pridejOtazku("napálit, podvést, oklamat", "dupe");
	pridejOtazku("povinnosti, úkoly", "duties");
	pridejOtazku("povinnosti, úkoly", "duty");
	pridejOtazku("hospodářská trestná činnost, hospodářská kriminalita", "economic crime");
	pridejOtazku("prodejce na internetu", "e-dealer");
	pridejOtazku("vzdělávání a výcvik", "education and training");
	pridejOtazku("efektivita a účinnost", "efficiency and effectiveness");
	pridejOtazku("volit", "elect");
	pridejOtazku("elektronika", "electrical equipment");
	pridejOtazku("vyhnout se (obratně)", "elude");
	pridejOtazku("technika, s jejíž pomocí se pachatel vyhne prozrazení", "eluding technique");
	pridejOtazku("pevně zasadit, zapustit", "embed");
	pridejOtazku("zpronevěra, defraudace", "embezzlement");
	pridejOtazku("zahrnovat", "embrace");
	pridejOtazku("objevit se", "emerge");
	pridejOtazku("pomoc v naléhavých případech", "emergency assistance");
	pridejOtazku("vybavení pro případ nouze, záchranné zařízení", "emergency equipment");
	pridejOtazku("mimořádná událost, stav nouze", "emergency event");
	pridejOtazku("zásahová jednotka", "emergency response team");
	pridejOtazku("státní zaměstnanec", "employee of the state");
	pridejOtazku("spodporovat, stimulovat nové uchazeče", "encourage new recruit");
	pridejOtazku("vynutit si, prosadit", "enforce");
	pridejOtazku("prosazovat právo", "enforce law");
	pridejOtazku("prosazovat zákon", "enforce the law");
	pridejOtazku("zabývat se, praktikovat", "engage in");
	pridejOtazku("motor", "engine");
	pridejOtazku("posilovat", "enhance");
	pridejOtazku("posílení", "enhancing");
	pridejOtazku("znamenat", "entail");
	pridejOtazku("vstoupit, vstup", "enter");
	pridejOtazku("svěřit", "entrust");
	pridejOtazku("vstup", "entry");
	pridejOtazku("trestné činy proti životnímu prostředí", "environmental crime");
	pridejOtazku("nárameník", "epaulette");
	pridejOtazku("bezpečnostní autosklo", "EPG, enhanced protection glazing");
	pridejOtazku("vybavení", "equipment");
	pridejOtazku("útěk, utéct, uprchnout", "escape");
	pridejOtazku("špionáž, vyzvědačství", "espionage");
	pridejOtazku("zásadní", "essencial");
	pridejOtazku("ustanovit, zřídit", "establish");
	pridejOtazku("stálý stav", "establishment");
	pridejOtazku("připravit rozpočet", "establish the budget");
	pridejOtazku("etnické čistky", "ethnic cleansing");
	pridejOtazku("Evropský soud pro lidská práva", "European Court of Human Rights");
	pridejOtazku("Evropský soudní dvůr", "European Court of Justice");
	pridejOtazku("nakonec změněný", "eventually overturned");
	pridejOtazku("důkaz, důkazy", "evidence");
	pridejOtazku("prověřování", "examination");
	pridejOtazku("zkoumat, přezkoumat, přešetřit", "examine");
	pridejOtazku("překročit, přesáhnout", "exceed");
	pridejOtazku("nepřímá, spotřební daň", "excise duty");
	pridejOtazku("výhradně", "exclusively");
	pridejOtazku("popravit", "execute");
	pridejOtazku("poprava", "execution");
	pridejOtazku("Výkonný výbor", "Executive committee");
	pridejOtazku("ilustrovat, doložit příkladem", "exemplify");
	pridejOtazku("uplatňovat, vykonávat", "exercise");
	pridejOtazku("uplatňovat pravomoc", "exercise authority");
	pridejOtazku("vykonávat, plnit své povinnosti, vykonávat službu", "exercise one's duties");
	pridejOtazku("očekávat", "expect");
	pridejOtazku("důkaz prokázaný soudním znalcem", "expert evidence");
	pridejOtazku("znalecký posudek", "expertise statement");
	pridejOtazku("vystavit, odhalit", "expose");
	pridejOtazku("vnější hranice", "external border");
	pridejOtazku("vydírání, vymáhání, vynucování", "extortion");
	pridejOtazku("extrémní jev", "extreme fenomenon");
	pridejOtazku("ulehčit, pomoci", "acilitate");
	pridejOtazku("usnadnit, zjednodušit", "acilitate");
	pridejOtazku("usnadňující", "acilitating");
	pridejOtazku("selhat, neuspět", "ail");
	pridejOtazku("zkrachovat", "ail");
	pridejOtazku("spravedlnost, čestnost, slušnost", "airness");
	pridejOtazku("goods padělané zboží", "ake");
	pridejOtazku("smrtelný", "atal");
	pridejOtazku("těžký zločinec", "elon");
	pridejOtazku("závažný trestný čin", "elony");
	pridejOtazku("těžký zločin", "elony");
	pridejOtazku("smyšlený, románový", "ictional");
	pridejOtazku("spis", "ile");
	pridejOtazku("vyplňovat hlášení", "ile report");
	pridejOtazku("konečné řešení (Židovské otázky)", "inal solution");
	pridejOtazku("finanční podvody", "inancial fraud");
	pridejOtazku("finanční zisk", "inancial gain");
	pridejOtazku("zjištění", "inding");
	pridejOtazku("poznatek", "inding");
	pridejOtazku("pokuta, pokutovat", "ine");
	pridejOtazku("otisk prstu", "ingerprint");
	pridejOtazku("identificationdaktyloskopie", "ingerprint");
	pridejOtazku("špička prstu", "ingertip");
	pridejOtazku("střelné zbraně", "firearms");
	pridejOtazku("první pomoc", "first aid");
	pridejOtazku("instalování, instalace", "fitting");
	pridejOtazku("uprchnout, utéci", "flee");
	pridejOtazku("záplavy povodně", "floods");
	pridejOtazku("pohrávat si s", "fool around with");
	pridejOtazku("video/foto záznam, dokumentace", "footage");
	pridejOtazku("zakazovat", "forbid");
	pridejOtazku("násilí, síla", "force");
	pridejOtazku("násilím něčeho dosáhnout, vynutit si vstup, vypáčit, vyrazit", "force");
	pridejOtazku("násilný vstup do objektu, budovy, bytu", "forced entry");
	pridejOtazku("soudní, forenzní", "forensic");
	pridejOtazku("kriminalistická laboratoř", "forensic laboratory");
	pridejOtazku("forenzní věda", "forensic science");
	pridejOtazku("padělat", "forge");
	pridejOtazku("padělání", "forgery");
	pridejOtazku("drůbež", "fowl");
	pridejOtazku("úlomek, střep", "fragment");
	pridejOtazku("roztříštění", "fragmentation");
	pridejOtazku("roztříštěný", "fragmented");
	pridejOtazku("podvod", "fraud");
	pridejOtazku("podvodník", "fraudster");
	pridejOtazku("podvodné e-maily", "fraudulent emails");
	pridejOtazku("podvody pracovníků uvnitř firmy", "fraud within corporations");
	pridejOtazku("volný pohyb osob", "free movement of people");
	pridejOtazku("tření", "friction");
	pridejOtazku("osoba na útěku, uprchlík", "fugitive");
	pridejOtazku("uprchlíci", "fugitives");
	pridejOtazku("plnit", "fulfil");
	pridejOtazku("denní studium", "full time study");
	pridejOtazku("další odborné/profesní vzdělávání/výcvik", "further vocational training");
	pridejOtazku("zisk", "gain");
	pridejOtazku("získat", "gain");
	pridejOtazku("kus oděvu, nebo prádla", "garment");
	pridejOtazku("oděvy", "garments");
	pridejOtazku("shromažďovat fakta", "gather facts");
	pridejOtazku("zjišťovat skutečnosti/fakta", "gather facts");
	pridejOtazku("Valné shromáždění", "General Assembly");
	pridejOtazku("Generální sekretariát", "General Secretariat");
	pridejOtazku("genetika", "genetics");
	pridejOtazku("genocida, masakr, vyhlazení", "genocide");
	pridejOtazku("vejít v kontakt", "get in touch");
	pridejOtazku("účastnit se", "get involved");
	pridejOtazku("vyvolat", "give rise");
	pridejOtazku("zasklení", "glazing");
	pridejOtazku("přesahovat rámec", "go beyond");
	pridejOtazku("zboží", "goods");
	pridejOtazku("propadnout, neprávem si přivlastnit", "grab");
	pridejOtazku("grafitti, nápisy na zdech a veřejně přístupných místech", "graffiti");
	pridejOtazku("těžké ublížení na zdraví", "grievous bodily harm");
	pridejOtazku("pěstování", "growing");
	pridejOtazku("host", "guest");
	pridejOtazku("pravidlo, pokyn", "guideline");
	pridejOtazku("vinen", "guilty");
	pridejOtazku("proniknout do jiného počítače", "hack another computer");
	pridejOtazku("bránit, překážet", "hamper");
	pridejOtazku("manipulovat, zacházet s něčím", "handle");
	pridejOtazku("překupnictví kradeného zboží", "handling stolen goods");
	pridejOtazku("rukopis", "handwriting");
	pridejOtazku("písmoznalectví", "handwriting identification");
	pridejOtazku("nečinně postávat, potloukat se kolem", "hang around, hang round");
	pridejOtazku("přístavní hlídka", "harbor patrol");
	pridejOtazku("újma, ublížení, zranění", "harm");
	pridejOtazku("trestné činy rasově motivované a proti lidskosti", "hate crimes");
	pridejOtazku("extremisté, skupiny", "hate groups");
	pridejOtazku("nenávist, zášť vůči konkrétním skupinám", "hatred toward particular groups");
	pridejOtazku("mít právní subjektivitu", "have legal personality");
	pridejOtazku("ústředí, centrála, ředitelství", "headquarters");
	pridejOtazku("podvody v poskytování zdravotní péče", "health care fraud");
	pridejOtazku("projednat", "hear a case");
	pridejOtazku("vyslechnout", "hear a person");
	pridejOtazku("projednávání, slyšení", "hearing");
	pridejOtazku("výslech", "hearing");
	pridejOtazku("nejvyšší soud", "High Court");
	pridejOtazku("závažná hiospodářská trestná činnost", "high-impact economic crime");
	pridejOtazku("vyšší státní zástupce", "High Public Prosecutornej");
	pridejOtazku("dálniční policie", "highway patrol");
	pridejOtazku("únos (letadla)", "hijacking");
	pridejOtazku("ujetí z místa nehody", "hit-and-run");
	pridejOtazku("domácí vězení", "home confinement");
	pridejOtazku("ministr vnitra", "Home Secretary");
	pridejOtazku("vražda, zabití", "homicide");
	pridejOtazku("homofobní, nemající rád homosexuály", "homophobic");
	pridejOtazku("jednotka jízdní policie", "horseback unit");
	pridejOtazku("nepřátelství, zášť, odpor", "hostility");
	pridejOtazku("Sněmovna lordů", "House of Lords");
	pridejOtazku("obrovský, ohromný", "huge");
	pridejOtazku("obrovsky", "hugely");
	pridejOtazku("obchodování s lidmi", "human trafficking");
	pridejOtazku("utiskovat, utlačovat, ponižovat", "humiliate");
	pridejOtazku("útisk, útlak", "humiliation");
	pridejOtazku("identifikační údaje", "dentity date");
	pridejOtazku("nemajetkový podvod", "dentity fraud");
	pridejOtazku("krádež identity", "dentity theft");
	pridejOtazku("zneužití, krádež identity, poškozování cizích práv", "dentity theft");
	pridejOtazku("zapalování", "ignition");
	pridejOtazku("klíč k zapalování", "ignition key");
	pridejOtazku("nelegální stahování", "illegal downloading");
	pridejOtazku("nelegální obchod s drogami", "illegal drug trade");
	pridejOtazku("nezákonná výroba drog", "illicid drug production");
	pridejOtazku("přistěhovalectví, imigrace", "immigration");
	pridejOtazku("zařízení, zabraňující v odjezdu s vozidlem", "immobiliser");
	pridejOtazku("dopad, účinek", "impact");
	pridejOtazku("odolný vůči nárazu", "impact-resistant");
	pridejOtazku("poškození", "impairment");
	pridejOtazku("provádět, uskutečňovat", "implement");
	pridejOtazku("předpokládat, obsahovat", "imply");
	pridejOtazku("uložit, uvalit", "impose");
	pridejOtazku("trest odnětí svobody", "imprisonment");
	pridejOtazku("nevyčíslitelný, nezměrný", "incalculable");
	pridejOtazku("zbavení způsobilosti k právním úkonům", "incapacitation");
	pridejOtazku("incest, sexuální zneužití mezi příbuznými", "incest");
	pridejOtazku("zahrnutý do pořadu jednání", "included on the agenda");
	pridejOtazku("rozšiřující se nabídka, sortiment", "increasing range");
	pridejOtazku("obscénnost, nemravnost", "indecency");
	pridejOtazku("nekonečně", "indefinitely");
	pridejOtazku("samostatný při rozhodování o úkolech a akcích", "independent in operational matters");
	pridejOtazku("nezávislýúředník", "independent office holder");
	pridejOtazku("žalovatelný trestný čin, čin soudně trestný", "indictable offence");
	pridejOtazku("obžaloba, obžalovací spis", "indictment");
	pridejOtazku("průmyslová špionáž", "industrial espionage");
	pridejOtazku("výslech", "inerview");
	pridejOtazku("způsobit", "inflict");
	pridejOtazku("porušení, přestoupení, přestupek", "infraction");
	pridejOtazku("porušit právo, zákon", "infringe");
	pridejOtazku("vynalézavost, důvtipnost", "ingenuity");
	pridejOtazku("neodmyslitelná část", "inherent part");
	pridejOtazku("zranění", "injury");
	pridejOtazku("nevinen, nevinný", "innocent");
	pridejOtazku("dokazovat před soudem", "inquire");
	pridejOtazku("dokazování před soudem, vyšetřování", "inquiry");
	pridejOtazku("zneužívání informací v obchodním styku", "insider trading");
	pridejOtazku("ředitel ředitelství policie", "Inspector of Constabulary");
	pridejOtazku("inspirovat, vnuknout nápad", "inspire");
	pridejOtazku("instalace", "installing");
	pridejOtazku("urážka", "insult");
	pridejOtazku("pojištění", "insurance");
	pridejOtazku("pojišťovací podvody", "insurance fraud");
	pridejOtazku("duševní vlastnictví", "intellectual property");
	pridejOtazku("crimezcizení duševního vlastnictví", "intellectual property");
	pridejOtazku("zpravodajská, výzvědná služba", "intelligence agency");
	pridejOtazku("úmysl", "intent");
	pridejOtazku("Mezinárodní trestní soud", "International Criminal Court");
	pridejOtazku("Mezinárodní trestní tribunál", "International Criminal Tribunal");
	pridejOtazku("mezinárodní vazby", "international ties");
	pridejOtazku("internetová kriminalita", "Internet crime");
	pridejOtazku("činit nátlak a způsobit rozklad celých komunit", "intimidate and disrupt entire communities");
	pridejOtazku("útlak a násilí", "intimidation and violence");
	pridejOtazku("vyšetřovat", "investigate");
	pridejOtazku("vyšetřovat vloupání", "investigate a burglary");
	pridejOtazku("vyšetřování", "investigation");
	pridejOtazku("vyšetřovací", "investigative");
	pridejOtazku("nedotknutelnost", "inviolability");
	pridejOtazku("nedbalostní zabití", "involuntary manslaughter");
	pridejOtazku("zahrnovat", "involve");
	pridejOtazku("zapojení se čeho, angažování se v čem", "involvement");
	pridejOtazku("nezávislá policejní komise pro vyšetřování stížností", "IPCC");
	pridejOtazku("otázky, problémy", "issue");
	pridejOtazku("položka, část, vydat, vyslat, zveřejnit, vystavit", "issue");
	pridejOtazku("zveřejnit omluvu", "issue an appology");
	pridejOtazku("položka, věc", "item");
	pridejOtazku("věznice, vězení, uvěznit, poslat do vězení", "jail");
	pridejOtazku("bezohledné přecházení ulice", "jaywalking");
	pridejOtazku("dres", "jersey");
	pridejOtazku("šperk, klenot", "jewel");
	pridejOtazku("šperky, klenoty", "jewellery");
	pridejOtazku("židovský", "Jewish");
	pridejOtazku("Židé", "Jews");
	pridejOtazku("soudce", "judge");
	pridejOtazku("justice", "judiciary");
	pridejOtazku("služebně mladší policisté", "junior officers");
	pridejOtazku("soudní pravomoc, jurisdikce", "jurisdiction");
	pridejOtazku("jurisdikce, soudní pravomoc", "jurisdiction");
	pridejOtazku("porota", "jury");
	pridejOtazku("soudní řízení za přítomnosti poroty", "jury trial");
	pridejOtazku("Ministerstvo spravedlnosti", "Justice Department");
	pridejOtazku("oprávěná obava", "justified concern");
	pridejOtazku("mladistvý", "juvenile");
	pridejOtazku("soud pro mladistvé", "juvenile court");
	pridejOtazku("kriminalita mladistvých", "juvenile delinquency");
	pridejOtazku("mladistvý provinilec", "juvenile delinquent");
	pridejOtazku("vesklíčové operační úkoly", "key operational objecti");
	pridejOtazku("kopnout", "kick");
	pridejOtazku("únos osoby", "kidnapping");
	pridejOtazku("únos dětí prostřednictvím chatů", "kidnapping children via chat rooms");
	pridejOtazku("zabití, usmrcení v sebeobraně", "killing in self defence");
	pridejOtazku("chyba, omyl", "lapse");
	pridejOtazku("odcizení cizího majetku", "larceny");
	pridejOtazku("krádež, rozkrádání", "larceny");
	pridejOtazku("odcizení, krádež", "larceny");
	pridejOtazku("zahájit, spustit", "launch");
	pridejOtazku("porušení práva, zákona", "law-breaking");
	pridejOtazku("bezpečnostní složky, prosazování zákona, policie, úřad šerifa", "law enforcement");
	pridejOtazku("orgány činné v trestním řízení", "law enforcement authorities");
	pridejOtazku("policisté, příslušníci bezpečnostních složek", "law enforcement officers");
	pridejOtazku("vést, řídit", "lead");
	pridejOtazku("schopnost vést, řídit", "leadership");
	pridejOtazku("letáky a plakáty", "leaflets and posters");
	pridejOtazku("právní následky", "legal consequences");
	pridejOtazku("právní zastoupení", "legal counsel");
	pridejOtazku("léky na recept", "legal prescription drugs");
	pridejOtazku("legislativní nástroj", "legislative tool");
	pridejOtazku("podrobně, do detailu", "length");
	pridejOtazku("styčný úřad", "liaison office");
	pridejOtazku("trest odnění svobody na doživotí", "life imprisonment");
	pridejOtazku("celoživotní vzdělávání", "lifelong study");
	pridejOtazku("omezené pravomoci", "limited powers");
	pridejOtazku("výkon služby", "line of duty");
	pridejOtazku("odhazování odpadků", "littering");
	pridejOtazku("hospodářské zvíře", "livestock");
	pridejOtazku("nabitá zbraň", "loaded gun");
	pridejOtazku("půjčka", "loan");
	pridejOtazku("místní územní celky", "local authority areas");
	pridejOtazku("daně odváděné obecnímu úřadu, který je má ke své dispozici", "local council tax");
	pridejOtazku("místní samospráva", "local government");
	pridejOtazku("místní policejní instituce a její představitelé", "local police authority");
	pridejOtazku("vypátrání, nalezení", "location");
	pridejOtazku("logistika", "logistics");
	pridejOtazku("soudce nižšího soudu", "magistrate");
	pridejOtazku("úředník se soudní pravomocí", "magistrate");
	pridejOtazku("městský soud", "Magistrate court");
	pridejOtazku("nižší soud s omezenou jurisdikcí, zabývající se méně závažnými trestnými činy", "Magistrate's Court");
	pridejOtazku("udržovat, vést, provádět, držet, posílit, podpořit", "maintain");
	pridejOtazku("uchovávat záznamy", "maintain records");
	pridejOtazku("podpora", "maintenance");
	pridejOtazku("tvořit, skládat se, představovat", "make up");
	pridejOtazku("manažerské dovednosti", "management skills");
	pridejOtazku("zabití člověka v afektu, nebo z nedbalosti, neúmyslné zabití", "manslaughter");
	pridejOtazku("výroba", "manufacture");
	pridejOtazku("výroba", "manufacturing");
	pridejOtazku("znásilnění mezi partnery v manželském svazku", "marital rape");
	pridejOtazku("stopa, skvrna, šlápota", "mark");
	pridejOtazku("spotřebitelské podvody pomocí médií (internet, telemarketing)", "mass marketing fraud");
	pridejOtazku("masový vrah (str. 93)", "mass murderer");
	pridejOtazku("magisterský stupeň studia", "Master Degree");
	pridejOtazku("zralost, vyspělost", "maturity");
	pridejOtazku("identifikační označení", "means of identification");
	pridejOtazku("zdravotní a životní pojištění", "medical and life insurance");
	pridejOtazku("lékařská prohlídka", "medical exam");
	pridejOtazku("zmínit", "mention");
	pridejOtazku("zboží", "merchandise");
	pridejOtazku("Metropolitní policie města Londýna", "Metropolitan Police");
	pridejOtazku("oddělení metropolitní policie pro vyšetřování případů znásilnění", "Metropolitan Police Rape Unit");
	pridejOtazku("poddůstojnická hodnost", "middle rank");
	pridejOtazku("Ministerstvo vnitra", "Ministry of the Interior, (Affairs)");
	pridejOtazku("nezletilé osoby", "minors");
	pridejOtazku("neprofesionální řízení, chování", "misconduct");
	pridejOtazku("přečin, méně závažný trestný čin", "misdemeanor");
	pridejOtazku("pohřešovaná osoba", "missing person");
	pridejOtazku("zneužití", "misuse");
	pridejOtazku("vytvořit, modelovat", "model");
	pridejOtazku("vykonávat sexuální nátlak", "molest");
	pridejOtazku("sexuální nátlak", "molestation");
	pridejOtazku("pachatel sexuálního nátlaku", "molester");
	pridejOtazku("praní peněz", "money laundering");
	pridejOtazku("hypotéční podvody", "mortgage fraud");
	pridejOtazku("pravidla silničního provozu", "motor vehicle laws");
	pridejOtazku("krádež motorového vozidla", "motor vehicle theft");
	pridejOtazku("mnohonásobný, mnohočetný", "multiple");
	pridejOtazku("městský", "municipal");
	pridejOtazku("vražda, zavrařdit, úkladná vražda", "murder");
	pridejOtazku("vražedná zbraň", "murder weapon");
	pridejOtazku("smlouva o vzájemné pomoci", "mutual aid agreement");
	pridejOtazku("celostátní, státní příslušník", "national");
	pridejOtazku("Národní ústředna", "National Central Bureau");
	pridejOtazku("státní znak", "national emblem");
	pridejOtazku("národnost", "nationality");
	pridejOtazku("národní bezpečnostní strategie", "National Security Strategy");
	pridejOtazku("indiáni", "Native Americans");
	pridejOtazku("nacista, nacistický", "Nazi");
	pridejOtazku("nedbalost, nepozornost", "negligence, carelessness");
	pridejOtazku("neonacista", "neo-Nazi");
	pridejOtazku("neopakovatelný úkon", "non-recurring act");
	pridejOtazku("oznámení, výzvy, žádosti, pátrací oběžníky", "notices");
	pridejOtazku("cíl, operační cíl, úkol, plán", "objective");
	pridejOtazku("povinen", "obliged");
	pridejOtazku("dodržování", "observance");
	pridejOtazku("sledovat", "observe");
	pridejOtazku("mařit", "obstruct");
	pridejOtazku("obdržet", "obtain");
	pridejOtazku("získat", "obtain");
	pridejOtazku("vyslovit odsuzující rozsudek", "obtain conviction");
	pridejOtazku("očividný", "obvious");
	pridejOtazku("činnost při výkonu povolání", "occupational crimetr");
	pridejOtazku("pracovní zařazení", "occupational speciality");
	pridejOtazku("přihodit se, stát se", "occur");
	pridejOtazku("kriminální delikt, trestný čin", "offence");
	pridejOtazku("pohoršení, urážka", "offence");
	pridejOtazku("přestupek, přečin, trestný čin, porušení norem trestního a správního práva", "offence");
	pridejOtazku("pachatel, obviněný", "offender");
	pridejOtazku("urážlivý, útočný", "offensive");
	pridejOtazku("Úřad pro zahraniční styky a informace ÚZSIInformation, (OFRI)", "Office For Foreign Relations and");
	pridejOtazku("úředník, funkcionář", "official");
	pridejOtazku("report usnesení", "official");
	pridejOtazku("s ohledem na, vzhledem k", "on account of");
	pridejOtazku("k prohlídce, vystavený", "on display");
	pridejOtazku("ve službě, mimo službu", "on duty, off duty");
	pridejOtazku("v databázi", "on file");
	pridejOtazku("na základě", "on the basis");
	pridejOtazku("na návrh", "on the motion");
	pridejOtazku("otevřenost", "open attitude");
	pridejOtazku("provozovat spravovat", "operate");
	pridejOtazku("operační středisko", "operational centre");
	pridejOtazku("vedoucí operační pracovníci", "operational heads");
	pridejOtazku("příležitostný", "opportunist");
	pridejOtazku("prospěchář", "opportunist");
	pridejOtazku("možnost", "option");
	pridejOtazku("utrpení", "ordeal");
	pridejOtazku("organizovaný zločin", "organized crime");
	pridejOtazku("vládce tureckého impéria", "Ottoman");
	pridejOtazku("mimosoudní vyrovnání", "out of court settlement");
	pridejOtazku("fakturování vyšší částky", "overbilling");
	pridejOtazku("přetížený", "over-burdened");
	pridejOtazku("přeplněnný", "overcrowded");
	pridejOtazku("překrývat, krýt se s něčím zahrnovat", "overlap");
	pridejOtazku("cizí, zámořský", "overseas");
	pridejOtazku("práce přesčas", "overtime");
	pridejOtazku("změnit rozsudek", "overturn the sentence");
	pridejOtazku("administrativa", "paperwork");
	pridejOtazku("odstavec", "paragraph");
	pridejOtazku("ozbrojenci", "paramilitaries");
	pridejOtazku("podmíněné, dočasné propuštění", "parole");
	pridejOtazku("jednotlivý, určitý", "particular");
	pridejOtazku("specifická oblast", "particular field");
	pridejOtazku("kombinované studium", "part time study");
	pridejOtazku("vydávat se za někoho", "pass himself off");
	pridejOtazku("heslo", "password");
	pridejOtazku("hlídkovat", "patrol");
	pridejOtazku("hlídkové a průzkumné lety", "patrolling and reconnaisance flights");
	pridejOtazku("model, schéma", "pattern");
	pridejOtazku("předloha, původní e mail (jeden z významů)", "pattern");
	pridejOtazku("chodec", "pedestrian");
	pridejOtazku("trestní právo", "penal law");
	pridejOtazku("trest, pokuta", "penalty");
	pridejOtazku("trestná činnost spojená s machinacemi v penzijních fondech", "pension fund crime");
	pridejOtazku("vnímat, chápat", "perceive");
	pridejOtazku("neodkladný úkon", "peremptory act");
	pridejOtazku("vykonávat", "perform");
	pridejOtazku("výkon", "performance");
	pridejOtazku("vykonávat, plnit své povinnosti, vykonávat službu", "perform duties");
	pridejOtazku("křivá přísaha", "perjury");
	pridejOtazku("trvalé bydliště", "permanent residence");
	pridejOtazku("páchat trestnou činnost", "perpetrate crime");
	pridejOtazku("pachatel", "perpetrator");
	pridejOtazku("trvat", "persist");
	pridejOtazku("osobní účet", "personal account");
	pridejOtazku("osobní odpovědnost", "personal responsibility");
	pridejOtazku("vlastní potřeba", "personal use");
	pridejOtazku("osobní oddělení", "personnel department");
	pridejOtazku("respektovaná osoba, společností vážená osoba", "a person of respectability");
	pridejOtazku("maření soudního výkonu", "perverting the course of justice");
	pridejOtazku("benzínová čerpací stanice", "petrol station");
	pridejOtazku("méně závažná trestná činnost, drobná kriminalita", "petty crime, minor crime");
	pridejOtazku("lékárna", "pharmacy");
	pridejOtazku("jevy", "phenomena");
	pridejOtazku("jev", "phenomenon");
	pridejOtazku("metody k odcizení digitální identity uživatele", "phishing");
	pridejOtazku("falešné kopie původních e-mailů", "phishing emails");
	pridejOtazku("týrání svěřené osoby", "physical abuse");
	pridejOtazku("fyzické napadání", "physical abuse");
	pridejOtazku("kapesní krádeže", "pickpocketing");
	pridejOtazku("brát prášky", "pill-taking");
	pridejOtazku("civilní oblečení", "plainclothes");
	pridejOtazku("přiznání viny v některých bodech obžaloby", "plea bargaining");
	pridejOtazku("přiznat vinu", "plead guilty");
	pridejOtazku("prohlášení o vině, přiznání viny", "plead guilty");
	pridejOtazku("kleště, kombinačky, kleště na drát", "pliers");
	pridejOtazku("policie, policejní sbor, policisté", "police");
	pridejOtazku("Policejní akademie", "Police Academy");
	pridejOtazku("policejní orgány", "police authorities");
	pridejOtazku("velitel policie", "police chief");
	pridejOtazku("velitel", "Police Chief Officer");
	pridejOtazku("vyšší policejní škola", "Police College");
	pridejOtazku("disciplinární řízení vedené s příslušníkem policie", "police disciplinary procedure");
	pridejOtazku("policejní sbor", "police force");
	pridejOtazku("policejní služby", "policing výkon");
	pridejOtazku("policejní práce, výkon policejní činnosti, dohled, ochrana", "policing");
	pridejOtazku("výkon policejní činnosti", "policing");
	pridejOtazku("zákonodárce", "policymaker");
	pridejOtazku("politická příslušnost", "political affiliation");
	pridejOtazku("politické přesvědčení či víra", "political conviction or religion");
	pridejOtazku("část", "portion");
	pridejOtazku("vydávat se za koho", "pose");
	pridejOtazku("držení, vlastnění, přechovávání", "possessing");
	pridejOtazku("potenciální hrozby", "potential threats");
	pridejOtazku("jednoznačné, jasné poselství", "powerful message");
	pridejOtazku("obezřetnost, opatření", "precaution");
	pridejOtazku("cenný", "precious");
	pridejOtazku("převážně", "predominantly");
	pridejOtazku("předsudek, předpojatost", "prejudice");
	pridejOtazku("předsudek či nenávist", "prejudice or hate");
	pridejOtazku("ovlivnit předsudky koho, způsobit u koho zaujetí", "prejudice somebody, something");
	pridejOtazku("úkladná, chladnoktevná vražda", "premeditated and cold-blooded killing");
	pridejOtazku("úmyslný trsetný čin", "premeditated criminal act");
	pridejOtazku("úmyslný záměr", "premeditated intent");
	pridejOtazku("budova, provozovna", "premises");
	pridejOtazku("areál, komplex budov", "premises");
	pridejOtazku("prokázat se", "present identification");
	pridejOtazku("ochrana veřejného pořádku", "preservation of public tranquility");
	pridejOtazku("sídlo presidenta", "presidential seat");
	pridejOtazku("předstírat", "pretend");
	pridejOtazku("vyhnutelný", "preventable");
	pridejOtazku("předcházet páchání trestné činnosti", "prevent crime");
	pridejOtazku("prevence trestné činnosti", "prevention of crime");
	pridejOtazku("vazba předstižná", "preventive custody");
	pridejOtazku("zásada", "principle");
	pridejOtazku("trest odnětí svobody", "prison sentence");
	pridejOtazku("probační úředník", "probation officer");
	pridejOtazku("řízení proti uprchlému", "proceedings against a fugitive");
	pridejOtazku("řízení proti mladistvým", "proceedings against juveniles");
	pridejOtazku("zisk", "proceeds");
	pridejOtazku("předvést svědka", "produce a witness");
	pridejOtazku("profil absolventa policejní školy", "profile of a police graduate");
	pridejOtazku("zisk", "profit");
	pridejOtazku("výkonný, úspěšný", "prolific");
	pridejOtazku("významný, hlavní", "prominent");
	pridejOtazku("povýšit", "promote");
	pridejOtazku("podporovat", "promote");
	pridejOtazku("povýšení dle zákona o policii", "promotion from and within");
	pridejOtazku("napovědět", "prompt");
	pridejOtazku("důkaz", "proof");
	pridejOtazku("majetek", "property");
	pridejOtazku("majetek, vlastnictví, jměmí", "property");
	pridejOtazku("obžalovat, trestně stíhat", "prosecute");
	pridejOtazku("trestní řízení/stíhání", "prosecution");
	pridejOtazku("trestní stíhání", "prosecution");
	pridejOtazku("obžaloba, trestní / soudní stíhání", "prosecution");
	pridejOtazku("státní zástupce", "prosecutor");
	pridejOtazku("ochrana života a majetku", "protection of life and property");
	pridejOtazku("chránit životy a majetek", "protect lives and property");
	pridejOtazku("dokázat", "prove");
	pridejOtazku("poskytovat, zabezpečit", "provide");
	pridejOtazku("zajišťovat", "provide for");
	pridejOtazku("zajišťovat bezpečnost", "provide security");
	pridejOtazku("obor, pole působnosti", "province");
	pridejOtazku("předběžné zadržení", "provisional arrest");
	pridejOtazku("páčit, páčidlo", "pry");
	pridejOtazku("páčení", "prying");
	pridejOtazku("psychické týrání", "psychical abuse");
	pridejOtazku("psychotropní látky", "psychotropic substances");
	pridejOtazku("korupce veřejných činitelů", "public corruption");
	pridejOtazku("sveřejné instituce", "public entitie");
	pridejOtazku("vyloučením veřejnosti", "public is excludeds");
	pridejOtazku("veřejný pořádek", "public order");
	pridejOtazku("služba pořádkové policie", "Public Order Police");
	pridejOtazku("udeřit, dát ránu", "punch");
	pridejOtazku("potrestat, trestat", "punish");
	pridejOtazku("trestat", "punish");
	pridejOtazku("podléhající trestu, trestně stíhatelný", "punishable");
	pridejOtazku("trest", "punishment");
	pridejOtazku("zamýšlet", "purport");
	pridejOtazku("stíhat, sledovat", "pursue");
	pridejOtazku("odsoudit podmíněně", "put on probation");
	pridejOtazku("stáhnout obžalobu", "quash indictment");
	pridejOtazku("dotazy", "queries into");
	pridejOtazku("vyslýchat", "question");
	pridejOtazku("rasa", "race");
	pridejOtazku("předsudky z rasisitických a náboženských pohnutek", "racial and religious biases");
	pridejOtazku("rasistický, rasista", "racist");
	pridejOtazku("vyděrač", "racketeer");
	pridejOtazku("razie, zátah", "raid");
	pridejOtazku("železniční síť", "rail network");
	pridejOtazku("hodnost, služební zařazení", "rank");
	pridejOtazku("výkupné", "ransom");
	pridejOtazku("znásilnění, znásilnit", "rape");
	pridejOtazku("vyšetřování znásilnění", "rape inquiry");
	pridejOtazku("pachatel znásilnění", "rapist");
	pridejOtazku("zřídka", "rarely");
	pridejOtazku("logický důvod, princip", "rationale");
	pridejOtazku("dosáhnout, dostat se", "reach");
	pridejOtazku("důvod", "reason");
	pridejOtazku("rozlišovat", "recognize");
	pridejOtazku("doporučení", "recommendation");
	pridejOtazku("návrh na potrestání", "recommendation for punishment");
	pridejOtazku("záznam", "record");
	pridejOtazku("získat zpět", "recover");
	pridejOtazku("zpětné získání", "recovery");
	pridejOtazku("evidence", "register");
	pridejOtazku("remedy řádný opravný prostředek", "regular");
	pridejOtazku("vztahovat se k", "relate to");
	pridejOtazku("rozeslána", "relayed through");
	pridejOtazku("propustit", "release");
	pridejOtazku("spolehlivý", "reliable");
	pridejOtazku("neochotný", "reluctant");
	pridejOtazku("představovat hrozbu", "remain a danger");
	pridejOtazku("být vězněn, být zbaven os svobody", "remain in custody");
	pridejOtazku("prominutí, zmírnění trestu", "remission");
	pridejOtazku("dálkový ovladač", "remote control");
	pridejOtazku("poskytnout pomoc", "render assistance");
	pridejOtazku("repatriace postižených osob", "repatriation of afflicted people");
	pridejOtazku("oznámit, nahlásit", "report");
	pridejOtazku("oznámené trestné činy", "reported crimes");
	pridejOtazku("oznámit", "report to");
	pridejOtazku("oznámit policii", "report to the police");
	pridejOtazku("pověst, renomé", "reputation");
	pridejOtazku("požadavky", "requests");
	pridejOtazku("vyžadovat, požadovat", "require");
	pridejOtazku("požadované", "required");
	pridejOtazku("osvobodit, zachránit", "rescue");
	pridejOtazku("potvrdit trest smrti", "resentence to death");
	pridejOtazku("vyhradit, zajistit", "reserve");
	pridejOtazku("sídlit", "reside");
	pridejOtazku("cizinec s povolením k dlouhodobému pobytu", "residence alien");
	pridejOtazku("odolat", "resist");
	pridejOtazku("zdroje, prostředky", "resources");
	pridejOtazku("reagovat, odpovídat", "respond");
	pridejOtazku("reagovat", "respond");
	pridejOtazku("zodpovědnost", "responsibilit");
	pridejOtazku("odpovědný", "responsible");
	pridejOtazku("zodpovědný za", "responsible for");
	pridejOtazku("spočívat na", "rest on");
	pridejOtazku("podržet si, ponechat", "retain");
	pridejOtazku("odplata", "retribution");
	pridejOtazku("obnovit proces", "retry");
	pridejOtazku("vyvýšenina, hřbet", "ridge");
	pridejOtazku("analýza rizik", "risk analysis");
	pridejOtazku("bezpečnost silničního provozu", "road safety");
	pridejOtazku("bezpečnost a plynulost silničního provozu", "road safety and flow of road traffic");
	pridejOtazku("loupež, vyloupení, oloupení", "robbery");
	pridejOtazku("Římané", "Romans");
	pridejOtazku("cesta, trasa", "route");
	pridejOtazku("pravidlo, zásada", "rule");
	pridejOtazku("spustit antivirový program", "run anti-virus software");
	pridejOtazku("provozovat vězení", "run the prison");
	pridejOtazku("bezpečný", "safe");
	pridejOtazku("bezpečnostní", "safety");
	pridejOtazku("uspokojovat potřeby občanů", "satisfy civil society's needs");
	pridejOtazku("místo události", "scene");
	pridejOtazku("místo činu", "the scene of the crime, the crime scene");
	pridejOtazku("naplánovat, rozvrhnout", "schedule");
	pridejOtazku("vědecky", "scientifically");
	pridejOtazku("škrábanec, škrábat", "scratch");
	pridejOtazku("šroubovák", "screwdriver");
	pridejOtazku("pátrání, pátrat", "search");
	pridejOtazku("hledat, pátrat, prohledávat, vykonávat osobní prohlídku", "search");
	pridejOtazku("pátrání (více významů)", "searches");
	pridejOtazku("spotodlehlé, opuštěné místo", "secluded");
	pridejOtazku("Generální tajemník", "Secretary General");
	pridejOtazku("ministr vnitra", "Secretary of State for the Home Department");
	pridejOtazku("paragraf", "section");
	pridejOtazku("zajistit, ochránit", "secure");
	pridejOtazku("podvody s cennými papíry", "securities fraud");
	pridejOtazku("bezpečnost", "security");
	pridejOtazku("Bezpečnostní Informační Služba BIS", "Security Information Service, (SIS)");
	pridejOtazku("hledat, žádat o radu, pomoc", "seek advice");
	pridejOtazku("hledat osoby", "seek persons");
	pridejOtazku("vydat zatykač", "seek the arrest");
	pridejOtazku("zabavit", "seize");
	pridejOtazku("zabavení", "seizure");
	pridejOtazku("zřídka", "seldom");
	pridejOtazku("prodat", "sell");
	pridejOtazku("důstojnická hodnost", "senior rank");
	pridejOtazku("služebně výše postavený policista", "senior ranking officer");
	pridejOtazku("soudit", "sentence");
	pridejOtazku("druh trestu", "sentence");
	pridejOtazku("výrok rozsudku o trestu", "sentencing");
	pridejOtazku("ukládání trestů", "sentencing");
	pridejOtazku("několikanásobný vrah", "serial murderer (killer)");
	pridejOtazku("závažná trestná činnost, závažný trestný čin", "serious crime");
	pridejOtazku("vážně", "seriously");
	pridejOtazku("závažnost", "seriousness");
	pridejOtazku("závažný trestný čin", "serious offence");
	pridejOtazku("závažný sexuální trestný čin", "serious sexual offence");
	pridejOtazku("odpykávat si trest", "serve");
	pridejOtazku("sloužit občanům", "serve citizens");
	pridejOtazku("soubor efektivních nástrojů", "set of effective tools");
	pridejOtazku("přísně", "severely");
	pridejOtazku("našitý", "sewn on");
	pridejOtazku("sexuální zneužívání", "sexual abuse");
	pridejOtazku("sexuální útok, napadení", "sexual assault");
	pridejOtazku("předstíraný", "sham");
	pridejOtazku("ovlivňovat, utvářet, formovat", "shape");
	pridejOtazku("úřad šerifa", "Sheriff's Office");
	pridejOtazku("práce na směny", "shift work");
	pridejOtazku("krádež v obchodě", "shoplifting");
	pridejOtazku("získání hesla (PIN) uživatele odpozorováním", "shoulder surfing");
	pridejOtazku("nemocenská", "sick leave");
	pridejOtazku("vedle sebe, společně", "side by side");
	pridejOtazku("boční okénko", "side window");
	pridejOtazku("známky, stopy", "signs");
	pridejOtazku("samosoudce", "single judge");
	pridejOtazku("část", "slice");
	pridejOtazku("otevřít,odmknout", "slip");
	pridejOtazku("malé množství", "small amount");
	pridejOtazku("rozbít, zdemolovat, rozdrtit", "smash");
	pridejOtazku("rozbitá okna", "smashed windows");
	pridejOtazku("rychlé rozbití skla a vykradení vozidla", "smash & grab");
	pridejOtazku("hladký", "smooth");
	pridejOtazku("advokát, právník nižšího soudu", "solicitor");
	pridejOtazku("vyřešit trestný čin", "solve a crime");
	pridejOtazku("rafinovaný", "sophisticated");
	pridejOtazku("zdravý úsudek", "sound judgement");
	pridejOtazku("zvukový záznam", "sound recording");
	pridejOtazku("řada, série", "spate");
	pridejOtazku("jednotka užívající speciální zbraně a taktiky", "special weapons and tactics team");
	pridejOtazku("překročení povolené rychlosti", "speeding");
	pridejOtazku("rozeznat, zjistit", "spot");
	pridejOtazku("sexuální nátlak na partnera", "spousal abuse");
	pridejOtazku("snoubenec, snoubenka, druh/žka, manžel/ka", "spouse");
	pridejOtazku("stánkový prodej", "stall-front selling");
	pridejOtazku("podání vysvětlení", "statement of explanation");
	pridejOtazku("státní policie", "state police");
	pridejOtazku("státní zástupce", "State Prosecutor, Public Prosecutor");
	pridejOtazku("statistika", "statistics");
	pridejOtazku("dopuštět se krádeže, odcizit", "steal");
	pridejOtazku("volant", "steering wheel");
	pridejOtazku("zámek volantu", "steering wheel clamp");
	pridejOtazku("stanovit, určit", "stipulate");
	pridejOtazku("stockholmský syndrom, vazba oběti na pachateli", "Stockholm syndrome");
	pridejOtazku("pouliční trestná činnost spojená s obchodováním s drogami, zbraněmi", "street, drug-related, gun crime");
	pridejOtazku("udeřit, narazit", "strike ");
	pridejOtazku("bojovat o co", "struggle");
	pridejOtazku("boj, potírání", "struggle");
	pridejOtazku("podléhající, vystavený čemu", "subject to");
	pridejOtazku("vystavit něčemu", "subject to");
	pridejOtazku("předložit", "submit");
	pridejOtazku("předložit formální obvinění", "submit a formal complaint");
	pridejOtazku("značný", "substantial");
	pridejOtazku("trpět, utrpět", "suffer");
	pridejOtazku("trpět, strádat", "suffer from");
	pridejOtazku("urtpení", "suffering");
	pridejOtazku("trestný čin, který lze odsoudit sumárně", "summary offence");
	pridejOtazku("zkrácené přípravné trestní řízení", "summary pre-trial proceedings");
	pridejOtazku("předvolat", "summon");
	pridejOtazku("předvolání, obsílka", "summons");
	pridejOtazku("shrnout důkazy", "sum up the evidence");
	pridejOtazku("velmi rychlý způsob (jeden z významů)", "superhighway");
	pridejOtazku("nahradit, odstranit", "supersede");
	pridejOtazku("dohlížet, kontrolovat, řídit", "supervise");
	pridejOtazku("dozorovat", "supervise");
	pridejOtazku("dohlížet nad bezpečností a plynulostí silničního provozu", "supervise safety and the smoothness of traffic");
	pridejOtazku("dohled, dozor", "supervision");
	pridejOtazku("příkaz k dohledu probačním úředníkem", "supervision order");
	pridejOtazku("dodat, vybavit", "supply");
	pridejOtazku("evidence zatajené důkazy", "suppressed");
	pridejOtazku("nejvyšší, vrchní, vrcholný", "supreme");
	pridejOtazku("vyjít najevo", "surface");
	pridejOtazku("dohled, dozor (stálý)", "surveillance");
	pridejOtazku("sledování", "surveillance");
	pridejOtazku("přehled", "survey");
	pridejOtazku("náchylný k", "susceptible to");
	pridejOtazku("podezřelý", "suspect");
	pridejOtazku("podmíněné odsouzení, odložení výkonu trestu", "suspended sentence");
	pridejOtazku("podezření", "suspicion");
	pridejOtazku("podezřelý", "suspicious");
	pridejOtazku("podezřelá činnost", "suspicious activity");
	pridejOtazku("používat hrubé výrazy", "swear at");
	pridejOtazku("kroužit", "swirl");
	pridejOtazku("policista pod přísahou", "sworn officer");
	pridejOtazku("bojovat proti, potírat co", "tackle");
	pridejOtazku("zvládnout", "tackle");
	pridejOtazku("vypořádat se", "tackle");
	pridejOtazku("elektronicky monitorovat pomocí čipu", "tag");
	pridejOtazku("elektronické monitorování pomocí čipu", "tagging");
	pridejOtazku("využít něčeho, těžit z", "take advantage of");
	pridejOtazku("vybrat si daň", "take a toll");
	pridejOtazku("vzít do úvahy, vzít v potaz, přihlédnout k čemu", "take into account");
	pridejOtazku("vzít v úvahu", "take into consideration");
	pridejOtazku("vzít do vazby", "take into custody");
	pridejOtazku("manipulovat, poškodit", "tamper");
	pridejOtazku("cíl, objekt", "target");
	pridejOtazku("cíle", "targets");
	pridejOtazku("zvláštní jednotka", "task force");
	pridejOtazku("operační skupina, zásahová jednotka, komando", "task force");
	pridejOtazku("daň", "tax");
	pridejOtazku("evation daňový únik", "tax");
	pridejOtazku("rozpolcení, rozpolcenost1175. temptation pokušení", "tear");
	pridejOtazku("pokoušet osud", "tempt fate");
	pridejOtazku("výraz", "term");
	pridejOtazku("terorismus", "terrorism");
	pridejOtazku("vypovídat, ústně svědčit", "testify");
	pridejOtazku("svědčit u soudů", "testify in courts");
	pridejOtazku("krádež", "theft");
	pridejOtazku("krádež peněz", "theft of cash");
	pridejOtazku("potom, pak (knižně)", "thereafter");
	pridejOtazku("zde, v tomto ohledu", "therein");
	pridejOtazku("krádež, zlodějství", "thievery");
	pridejOtazku("hrozba", "threat");
	pridejOtazku("ohrožovat, zastrašovat", "threaten");
	pridejOtazku("hrozit, ohrožovat", "threaten");
	pridejOtazku("ohrozit bezpečnost", "threaten the safety");
	pridejOtazku("hrozby", "threats");
	pridejOtazku("pohrůžky", "threats");
	pridejOtazku("zamítnout", "throw out");
	pridejOtazku("úroveň, vrstva", "tier");
	pridejOtazku("svázat", "tie up");
	pridejOtazku("špička", "tip");
	pridejOtazku("zneužívat", "to abuse");
	pridejOtazku("bolet, trápit, sužovat", "to ail");
	pridejOtazku("být jmenován kým . . .", "to be appointed by");
	pridejOtazku("být zahanben", "to be ashamed");
	pridejOtazku("být propuštěn", "to be sacked");
	pridejOtazku("bojovat proti, potírat co", "to combat");
	pridejOtazku("snášenlivost léku, drogy, tolerance na drogu", "tolerance for drugs");
	pridejOtazku("nástroj", "tool");
	pridejOtazku("stopa, způsobená nástrojem", "toolmark");
	pridejOtazku("předejít, zabránit", "to prevent");
	pridejOtazku("mučení, mučit", "torture");
	pridejOtazku("mučení, týrání", "torture");
	pridejOtazku("tvrzené sklo, bezpečnostní sklo", "toughened safety glass");
	pridejOtazku("tvrdší, přísnější tresty", "tougher penalties");
	pridejOtazku("správní oblast, okres", "township");
	pridejOtazku("sledovat", "track");
	pridejOtazku("vystopovat", "track down");
	pridejOtazku("provoz, ruch", "traffic");
	pridejOtazku("nedovolené, nezákonné obchodování, kšeftování", "trafficking");
	pridejOtazku("monitorování dopravy", "traffic monitoring");
	pridejOtazku("služba dopravní policie", "Traffic Police");
	pridejOtazku("příslušník služby dopravní policie, dopravní policista", "traffic warden");
	pridejOtazku("provádět výcvik a školit", "train ");
	pridejOtazku("výcvikové centrum", "Training Center");
	pridejOtazku("postoupit", "transfer");
	pridejOtazku("transsexuálové", "transgender people");
	pridejOtazku("klíč se zabudovaným čipem", "transponder key");
	pridejOtazku("cestovní doklady", "travel documents");
	pridejOtazku("vlastizrada, velezrada", "treason");
	pridejOtazku("Ministerstvo financí", "Treasury Department");
	pridejOtazku("terapie, léčba", "treatment");
	pridejOtazku("neoprávněné vniknutí", "trespass");
	pridejOtazku("přečin, proviění", "trespass");
	pridejOtazku("strestné činy, které lze projednávat u nižšího i vyššího soudu", "triable either way offence");
	pridejOtazku("hlavní líčení", "trial");
	pridejOtazku("kmenový", "tribal");
	pridejOtazku("podvést,klamat", "trick");
	pridejOtazku("třístranné vztahy", "tripartite relationship");
	pridejOtazku("policista", "trooper");
	pridejOtazku("otáčení", "turnig");
	pridejOtazku("absolutní popření lidských práv", "ultimate denial of human rights");
	pridejOtazku("neoprávněný", "unauthorized");
	pridejOtazku("bezpodmíněné propuštění", "unconditional discharge");
	pridejOtazku("tajný", "undercover");
	pridejOtazku("podcenit", "underestimate");
	pridejOtazku("podvodný, lstivý", "underhand");
	pridejOtazku("základní", "underlying");
	pridejOtazku("být zásadním prvkem (jeden z významů)", "underlying");
	pridejOtazku("pod rouškou", "under the guis");
	pridejOtazku("neporušený", "undisturbed");
	pridejOtazku("neopodstatněné a zlomyslné stížnosti", "unfounded and malicious complaints");
	pridejOtazku("mrtvoly neznámé totožnosti", "unidentified bodies");
	pridejOtazku("uniformovaní policisté", "uniformed police officers");
	pridejOtazku("jedinečný", "unique");
	pridejOtazku("vlastní heslo, které zná pouze uživatel", "unique password");
	pridejOtazku("Všeobecná deklarace lidských práv", "the Universal Declaration of Human Rights");
	pridejOtazku("nedovolené shromažďování", "unlawful assembly");
	pridejOtazku("nevyřešené trestné činy", "unsolved crimes");
	pridejOtazku("neochota", "unvillingness");
	pridejOtazku("nedobrovolní uživatelé", "unwilling users");
	pridejOtazku("vylepšení, inovace", "upgrading");
	pridejOtazku("obtížný boj", "uphill battle");
	pridejOtazku("městský", "urban");
	pridejOtazku("uživatelé", "users");
	pridejOtazku("účty za služby domácnostem (elek,plyn, voda ...)", "utility bills");
	pridejOtazku("potvrdit (platnost), ověřit", "validate");
	pridejOtazku("hodnota, cena", "value");
	pridejOtazku("zničené automobily", "vandalised cars");
	pridejOtazku("vandalství, záměrné pustošení, vandalismus", "vandalism");
	pridejOtazku("velký počet,mnoho", "variety");
	pridejOtazku("lišit se podle jurisdikce", "vary by jurisdiction");
	pridejOtazku("rozličný, proměnlivý", "varying");
	pridejOtazku("obrovský,ohromný", "vast");
	pridejOtazku("verbální napadání", "verbal abuse");
	pridejOtazku("verbální narážky, posměch", "verbal taunts");
	pridejOtazku("procedureprověřování", "verification");
	pridejOtazku("prověřit", "verify");
	pridejOtazku("prověřování (vhodnosti)", "vetting");
	pridejOtazku("poškozený, oběť", "victim");
	pridejOtazku("partner poškozený trestným činem", "victimized partner");
	pridejOtazku("porušit zákon", "violate law");
	pridejOtazku("porušovat práva", "violate the rights");
	pridejOtazku("zneužití funkce", "violation of trust");
	pridejOtazku("násilí", "violence");
	pridejOtazku("násilí proti skupině obyvatel a proti jednotlivci", "violence against a group of inhabitants and individuals");
	pridejOtazku("násilný", "violent");
	pridejOtazku("násilná trestná činnost, násilný trestný čin", "violent crime");
	pridejOtazku("narušit civilizované chování", "vitiate the civility");
	pridejOtazku("vražda, zabití", "voluntary manslaughter");
	pridejOtazku("provádět pěší obchůzku", "walk the beat");
	pridejOtazku("hledaná osoba", "a wanted person");
	pridejOtazku("válečné zločiny", "war crimes");
	pridejOtazku("skladiště", "warehouse");
	pridejOtazku("varovat", "warn");
	pridejOtazku("varování", "warning");
	pridejOtazku("vlna", "wave");
	pridejOtazku("pašování zbraní", "weapons smuggling");
	pridejOtazku("plakat", "weep");
	pridejOtazku("sociální jistota, sociální stát", "welfare");
	pridejOtazku("kde, v kterém", "wherein");
	pridejOtazku("trestní čin úředníkem, prac v administrativě, krim bílých límečků", "white-collar crime");
	pridejOtazku("kriminalita \"bílých límečků\", hospodářská tresná činnost", "white-collar crime");
	pridejOtazku("trestná tzv. \"bílých límečků\", hospodářská trestná činnost", "white-collar crime");
	pridejOtazku("čtvrti obydlené bělochy", "white neighbourhoods");
	pridejOtazku("rýha", "whorl");
	pridejOtazku("čelní sklo", "windscreen");
	pridejOtazku("s možností", "with a view to");
	pridejOtazku("výběr peněz z účtu", "withdrawal");
	pridejOtazku("s úmyslem", "with the intent to");
	pridejOtazku("svědek", "witness");
	pridejOtazku("být svědkem", "witness");
	pridejOtazku("hlídkovat, vykonávat pochůzky", "work on foot");
	pridejOtazku("světové dějiny", "world history");
	pridejOtazku("mající hodnotu", "worth");
	pridejOtazku("bezcenný", "worthless");
	pridejOtazku("vypracovat, sepsat úřední záznam", "write a report");
	pridejOtazku("listinný dokumen", "writing document");



}

function pridejOtazku(otazka, odpoved) {
	var q = {
		otazka: otazka,
		odpoved: odpoved
	};

	otazky.push(q);
}